import type { Stage } from '../types'

export const stageFive: Stage = {
  id: 'stage-5',
  order: 5,
  title: 'Collections',
  description: 'Keep related values together and work with them as a group.',
  lessons: [
    {
      id: 'stage-5-lesson-1',
      order: 1,
      title: 'One name, many values',
      shortTitle: 'Lists hold many values',
      summary: 'A list keeps related values together under one name.',
      learningGoal: 'Create a list and use its name to work with several related values.',
      conceptTags: ['list', 'collection', 'values'],
      steps: [
        {
          id: 'choose-a-clearer-group',
          content: [
            { type: 'paragraph', text: 'Several names can hold several scores. A list keeps the group under one name.' },
            { type: 'example', code: 'score1 = 12\nscore2 = 15\nscore3 = 9\n\nscores = [12, 15, 9]', caption: 'One list keeps the scores together.' },
          ],
          activity: {
            id: 'choose-the-score-collection',
            kind: 'choice',
            title: 'Which keeps the group together?',
            prompt: 'Which version gives all three scores one shared name?',
            required: true,
            options: [
              { id: 'one-list', text: 'scores = [12, 15, 9]' },
              { id: 'separate-names', text: 'score1 = 12, score2 = 15, score3 = 9' },
            ],
            correctOptionId: 'one-list',
            correctFeedback: 'Right — one list name gives us a way to work with the whole group.',
            incorrectFeedback: 'Look for the version that puts the values between square brackets.',
          },
        },
        {
          id: 'make-a-score-list',
          content: [{ type: 'paragraph', text: 'Square brackets make a list. Commas separate its items.' }],
          activity: {
            id: 'create-and-print-a-list',
            kind: 'code',
            title: 'Create a list',
            prompt: 'Create a list called scores with a few numbers, then print scores.',
            required: true,
            starterCode: '# Create a list called scores with a few numbers\n# Print scores',
            assessment: {
              kind: 'behavior',
              cases: [{ inputs: [], output: { mode: 'line-count', count: 1 } }],
              requirements: ['list-literal'],
            },
            hints: ['Put the values inside square brackets, separated by commas.', 'For example: scores = [12, 15, 9]'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-5-lesson-2',
      order: 2,
      title: 'Items have positions',
      shortTitle: 'Find an item by position',
      summary: 'Use a position in square brackets to get one item from a list.',
      learningGoal: 'Read list items by their position and discover that the first position is 0.',
      conceptTags: ['list', 'index', 'position'],
      steps: [
        {
          id: 'notice-the-first-positions',
          content: [
            { type: 'paragraph', text: 'A list keeps its items in order. Python labels the first position 0.' },
            { type: 'example', code: 'animals = ["cat", "dog", "rabbit"]\n\nprint(animals[0])\nprint(animals[1])' },
            { type: 'callout', tone: 'tip', text: 'Try the code and notice which item each number selects.' },
          ],
          activity: {
            id: 'predict-first-list-positions',
            kind: 'predict-output',
            title: 'Predict the first two items',
            prompt: 'What will Python print, in order?',
            required: true,
            code: 'animals = ["cat", "dog", "rabbit"]\nprint(animals[0])\nprint(animals[1])',
            expectedOutput: ['cat', 'dog'],
            hints: ['The first item is at position 0.', 'Position 1 is the second item: dog.'],
          },
        },
        {
          id: 'read-the-third-animal',
          content: [{ type: 'paragraph', text: 'The positions are 0, 1, 2, so rabbit is at position 2.' }],
          activity: {
            id: 'print-the-third-animal',
            kind: 'code',
            title: 'Get one item',
            prompt: 'Add one print instruction to show rabbit using its position in animals.',
            required: true,
            starterCode: 'animals = ["cat", "dog", "rabbit"]\nprint(animals[0])\nprint(animals[1])',
            assessment: {
              kind: 'behavior',
              cases: [{ inputs: [], output: { mode: 'exact', lines: ['cat', 'dog', 'rabbit'] } }],
              requirements: ['list-index'],
            },
            hints: ['The positions start at 0, so the third item is at position 2.', 'Add print(animals[2]).'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-5-lesson-3',
      order: 3,
      title: 'Boundaries again',
      shortTitle: 'A position outside the list',
      summary: 'A list only has items at positions it actually contains.',
      learningGoal: 'Connect a list length with the positions that are valid to read.',
      conceptTags: ['list', 'index', 'bounds', 'IndexError'],
      steps: [
        {
          id: 'observe-a-missing-position',
          content: [
            { type: 'paragraph', text: 'This list has three items, at positions 0, 1, and 2. Position 3 is just past the end.' },
            { type: 'example', code: 'animals = ["cat", "dog", "rabbit"]\nprint(animals[3])' },
            { type: 'callout', tone: 'note', text: 'Run it to see the real Python error. An IndexError means the requested position is not in the list.' },
          ],
          activity: {
            id: 'notice-the-list-index-error',
            kind: 'code',
            title: 'Notice the boundary',
            prompt: 'Run the example and read the error Python gives for position 3.',
            required: true,
            starterCode: 'animals = ["cat", "dog", "rabbit"]\nprint(animals[3])',
            assessment: { kind: 'runtime-error', exceptionName: 'IndexError' },
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-5-lesson-4',
      order: 4,
      title: 'Do something for every item',
      shortTitle: 'Loop over a list',
      summary: 'A for loop can visit each value in a list, one at a time.',
      learningGoal: 'Read a list loop as “for each animal in animals”.',
      conceptTags: ['list', 'for', 'sequence'],
      steps: [
        {
          id: 'visit-each-animal',
          content: [
            { type: 'paragraph', text: 'Read for animal in animals as “for each animal in animals”. The indented lines run once for every item.' },
            { type: 'example', code: 'animals = ["cat", "dog", "rabbit"]\n\nfor animal in animals:\n    print(animal)' },
          ],
          activity: {
            id: 'print-every-animal',
            kind: 'code',
            title: 'Visit every item',
            prompt: 'Write a for loop that prints each animal on its own line.',
            required: true,
            starterCode: 'animals = ["cat", "dog", "rabbit"]\n# Write a for loop that prints each animal',
            assessment: {
              kind: 'behavior',
              cases: [{ inputs: [], output: { mode: 'exact', lines: ['cat', 'dog', 'rabbit'] } }],
              requirements: ['sequence-loop'],
            },
            hints: ['Use for animal in animals:, then indent print(animal).', 'The loop variable takes each list item in turn.'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-5-lesson-5',
      order: 5,
      title: 'Combine collections with decisions',
      shortTitle: 'Choose items from a list',
      summary: 'A loop can visit every score while an if statement selects some of them.',
      learningGoal: 'Use a condition inside a list loop to print only values that pass it.',
      conceptTags: ['list', 'for', 'if', 'filter'],
      steps: [
        {
          id: 'keep-scores-at-least-seven',
          content: [
            { type: 'paragraph', text: 'The loop visits every score. The if statement decides which ones reach print().' },
            { type: 'example', code: 'scores = [4, 9, 2, 10, 7]\n\nfor score in scores:\n    if score >= 7:\n        print(score)' },
          ],
          activity: {
            id: 'print-scores-at-least-seven',
            kind: 'code',
            title: 'Keep the scores that pass',
            prompt: 'Print only the scores that are 7 or higher.',
            required: true,
            starterCode: 'scores = [4, 9, 2, 10, 7]\n# Loop through scores and print only values of 7 or higher',
            assessment: {
              kind: 'behavior',
              cases: [{ inputs: [], output: { mode: 'exact', lines: ['9', '10', '7'] } }],
              requirements: ['sequence-loop', 'conditional', 'comparison'],
            },
            hints: ['Put an if inside the for loop.', 'Use if score >= 7: and indent print(score) under it.'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-5-lesson-6',
      order: 6,
      title: 'Ask questions about collections',
      shortTitle: 'Count and check a list',
      summary: 'len() counts items, and in checks whether a value is in a collection.',
      learningGoal: 'Use len() and in to ask two useful questions about a list.',
      conceptTags: ['list', 'len', 'membership'],
      steps: [
        {
          id: 'predict-list-questions',
          content: [
            { type: 'paragraph', text: 'len() gives the number of items. The word in checks whether a value is present.' },
            { type: 'example', code: 'names = ["Mia", "Leo", "Ava"]\n\nprint(len(names))\nprint("Leo" in names)' },
          ],
          activity: {
            id: 'predict-count-and-membership',
            kind: 'predict-output',
            title: 'Predict two answers',
            prompt: 'What will Python print for the number of names and whether Leo is in the list?',
            required: true,
            code: 'names = ["Mia", "Leo", "Ava"]\nprint(len(names))\nprint("Leo" in names)',
            expectedOutput: ['3', 'True'],
            hints: ['There are three names.', 'Leo is one of the list items, so the second answer is True.'],
          },
        },
        {
          id: 'ask-about-a-list',
          content: [{ type: 'paragraph', text: 'len() and in answer different questions: how many, and whether one value is there.' }],
          activity: {
            id: 'print-count-and-membership',
            kind: 'code',
            title: 'Ask about names',
            prompt: 'Print how many names there are, then print whether Leo is in names.',
            required: true,
            starterCode: 'names = ["Mia", "Leo", "Ava"]\n# Print how many names there are\n# Print whether "Leo" is in names',
            assessment: {
              kind: 'behavior',
              cases: [{ inputs: [], output: { mode: 'exact', lines: ['3', 'True'] } }],
              requirements: ['length-call', 'membership-test'],
            },
            hints: ['Use print(len(names)) to print the count.', 'Use print("Leo" in names) for the True or False answer.'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-5-lesson-7',
      order: 7,
      title: 'Collections can change',
      shortTitle: 'Add an item to a list',
      summary: 'append() puts a new item at the end of a list.',
      learningGoal: 'Add one new item to an existing list with append().',
      conceptTags: ['list', 'mutation', 'append'],
      steps: [
        {
          id: 'add-an-item',
          content: [
            { type: 'paragraph', text: 'A program can change a list while it runs. append() adds one new item at the end.' },
            { type: 'example', code: 'shopping = ["milk", "bread"]\nshopping.append("apples")\nprint(shopping)' },
            { type: 'callout', tone: 'tip', text: 'This is one useful list operation. There is no need to learn the whole list toolbox yet.' },
          ],
          activity: {
            id: 'append-apples-to-shopping',
            kind: 'code',
            title: 'Add to the shopping list',
            prompt: 'Use append() to add apples, then print the shopping list.',
            required: true,
            starterCode: 'shopping = ["milk", "bread"]\n# Add apples to shopping\nprint(shopping)',
            assessment: {
              kind: 'behavior',
              cases: [{ inputs: [], output: { mode: 'exact', lines: ["['milk', 'bread', 'apples']"] } }],
              requirements: ['append-call'],
            },
            hints: ['Call append() on the list named shopping.', 'Write shopping.append("apples").'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-5-lesson-8',
      order: 8,
      title: 'Strings are collections too',
      shortTitle: 'Loop through text',
      summary: 'A string contains characters in order, so a loop and positions work with it too.',
      learningGoal: 'Transfer collection ideas from lists to the characters in a string.',
      conceptTags: ['string', 'sequence', 'for', 'index'],
      steps: [
        {
          id: 'see-text-as-a-sequence',
          content: [
            { type: 'paragraph', text: 'A word has characters in order. A for loop can visit each character, and [0] gets its first character.' },
            { type: 'example', code: 'word = "python"\n\nfor letter in word:\n    print(letter)\n\nprint(word[0])' },
          ],
          activity: {
            id: 'choose-how-to-visit-letters',
            kind: 'choice',
            title: 'How can Python visit each letter?',
            prompt: 'Which instruction gives letter each character in word, one at a time?',
            required: true,
            options: [
              { id: 'loop-over-word', text: 'for letter in word:' },
              { id: 'range-over-word', text: 'for letter in range(word):' },
            ],
            correctOptionId: 'loop-over-word',
            correctFeedback: 'Yes — a string is an ordered sequence of characters.',
            incorrectFeedback: 'Use the word itself after in; it already contains the characters in order.',
          },
        },
        {
          id: 'print-letters-and-first-letter',
          content: [{ type: 'paragraph', text: 'The same “for each” and position ideas work with text.' }],
          activity: {
            id: 'visit-letters-and-first-letter',
            kind: 'code',
            title: 'Use a word as a sequence',
            prompt: 'Print each letter in python on its own line, then print its first letter once more.',
            required: true,
            starterCode: 'word = "python"\n# Loop through word and print each letter\n# Print the first letter',
            assessment: {
              kind: 'behavior',
              cases: [{ inputs: [], output: { mode: 'exact', lines: ['p', 'y', 't', 'h', 'o', 'n', 'p'] } }],
              requirements: ['sequence-loop', 'subscript'],
            },
            hints: ['Use for letter in word: and indent print(letter).', 'Use print(word[0]) for the first character.'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-5-lesson-9',
      order: 9,
      title: 'Build: analyse some scores',
      shortTitle: 'Analyse some scores',
      summary: 'Use a list, a loop, and a decision to answer three questions about scores.',
      learningGoal: 'Print every score, select scores of 7 or higher, and count how many there are.',
      conceptTags: ['list', 'for', 'if', 'len', 'project'],
      steps: [
        {
          id: 'show-all-scores',
          content: [
            { type: 'paragraph', text: 'Start with the scores [8, 3, 10, 6, 9]. First, print every score.' },
            { type: 'callout', tone: 'tip', text: 'Keep the same scores in each small task. Focus on one new question at a time.' },
          ],
          activity: {
            id: 'print-every-project-score',
            kind: 'code',
            title: 'Show every score',
            prompt: 'Use a for loop to print every score on its own line.',
            required: true,
            starterCode: 'scores = [8, 3, 10, 6, 9]\n# Print each score',
            assessment: {
              kind: 'behavior',
              cases: [{ inputs: [], output: { mode: 'exact', lines: ['8', '3', '10', '6', '9'] } }],
              requirements: ['sequence-loop'],
            },
            hints: ['Loop with for score in scores:.', 'Indent print(score) inside the loop.'],
          },
        },
        {
          id: 'select-high-scores',
          content: [{ type: 'paragraph', text: 'Now keep only scores that are 7 or higher.' }],
          activity: {
            id: 'print-project-scores-at-least-seven',
            kind: 'code',
            title: 'Select the higher scores',
            prompt: 'Print only scores that are 7 or higher.',
            required: true,
            starterCode: 'scores = [8, 3, 10, 6, 9]\n# Loop through scores and print those that are at least 7',
            assessment: {
              kind: 'behavior',
              cases: [{ inputs: [], output: { mode: 'exact', lines: ['8', '10', '9'] } }],
              requirements: ['sequence-loop', 'conditional', 'comparison'],
            },
            hints: ['Use an if statement inside the loop.', 'Check if score >= 7 before printing it.'],
          },
        },
        {
          id: 'count-project-scores',
          content: [{ type: 'paragraph', text: 'Finally, ask how many scores are in the list. Do not add them up yet.' }],
          activity: {
            id: 'print-number-of-project-scores',
            kind: 'code',
            title: 'Count the scores',
            prompt: 'Print how many scores are in the list.',
            required: true,
            starterCode: 'scores = [8, 3, 10, 6, 9]\n# Print the number of scores',
            assessment: {
              kind: 'behavior',
              cases: [{ inputs: [], output: { mode: 'exact', lines: ['5'] } }],
              requirements: ['length-call'],
            },
            hints: ['len() gives the number of items in a collection.', 'Print len(scores).'],
          },
        },
      ],
      status: 'ready',
    },
  ],
}
