import type { Stage } from '../types'

const leaderboardPlayers = 'players = [\n    {"name": "Nova", "score": 84},\n    {"name": "Pixel", "score": 93},\n    {"name": "Echo", "score": 76}\n]'

const representationChoices = [
  { id: 'single-value', text: 'One value' },
  { id: 'list', text: 'A list' },
  { id: 'dictionary', text: 'A dictionary' },
  { id: 'list-of-records', text: 'A list of dictionaries' },
]

export const stageEight: Stage = {
  id: 'stage-8',
  order: 8,
  title: 'Representing Information',
  description: 'Choose useful structures for information about one thing or many.',
  lessons: [
    {
      id: 'stage-8-lesson-1',
      order: 1,
      title: 'The problem with parallel variables',
      shortTitle: 'Keep related values together',
      summary: 'Related values are easier to work with when the program keeps them together.',
      learningGoal: 'Recognise that several values describe one thing and group them in a record.',
      conceptTags: ['representation', 'dictionary', 'state'],
      steps: [
        {
          id: 'spot-related-values',
          content: [
            { type: 'paragraph', text: 'A name, age, and score can all describe the same student.' },
            { type: 'example', code: 'name = "Mia"\nage = 12\nscore = 88', caption: 'Three separate names for related information.' },
          ],
          activity: {
            id: 'recognise-one-student',
            kind: 'choice',
            title: 'What do these values describe?',
            prompt: 'The name, age, and score all belong to the same person. What would help keep them together?',
            required: true,
            options: [
              { id: 'one-record', text: 'One record with named fields' },
              { id: 'three-loops', text: 'Three separate loops' },
              { id: 'one-value', text: 'One number containing everything' },
            ],
            correctOptionId: 'one-record',
            correctFeedback: 'Right — these values describe one student, so one record can group them.',
            incorrectFeedback: 'Look for a representation that keeps values about one student together.',
          },
        },
        {
          id: 'group-a-students-information',
          content: [
            { type: 'paragraph', text: 'A dictionary groups values under meaningful keys, like labels on the information.' },
            { type: 'example', code: 'student = {"name": "Mia", "age": 12, "score": 88}\nprint(student["name"])' },
          ],
          activity: {
            id: 'make-a-student-record',
            kind: 'code',
            title: 'Make one student record',
            prompt: 'Put the name, age, and score into student, then print the name from the record.',
            required: true,
            starterCode: 'name = "Mia"\nage = 12\nscore = 88\nstudent = {}\nprint(student["name"])',
            assessment: {
              kind: 'behavior',
              cases: [{ inputs: [], output: { mode: 'exact', lines: ['Mia'] } }],
              requirements: ['dictionary-literal', 'dictionary-field-read'],
            },
            hints: ['Put the values inside { } using keys such as "name" and "age".', 'Make student a dictionary, then read student["name"].'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-8-lesson-2',
      order: 2,
      title: 'A record with named fields',
      shortTitle: 'Find a value by its key',
      summary: 'A dictionary key gives a value a meaningful way to be found.',
      learningGoal: 'Read values from a dictionary using their text keys.',
      conceptTags: ['dictionary', 'keys', 'record'],
      steps: [
        {
          id: 'read-named-fields',
          content: [
            { type: 'paragraph', text: 'Use the field name in square brackets to find its value.' },
            { type: 'example', code: 'student = {"name": "Mia", "age": 12, "score": 88}\nprint(student["age"])' },
          ],
          activity: {
            id: 'read-the-student-name-and-age',
            kind: 'code',
            title: 'Read two named fields',
            prompt: 'Print Mia’s name and age on separate lines. Fix the key that does not exist and add the other field.',
            required: true,
            starterCode: 'student = {"name": "Mia", "age": 12, "score": 88}\nprint(student["city"])',
            assessment: {
              kind: 'behavior',
              cases: [{ inputs: [], output: { mode: 'exact', lines: ['Mia', '12'] } }],
              requirements: ['dictionary-field-read'],
            },
            hints: ['The dictionary has name and age keys, not city.', 'Print student["name"], then student["age"].'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-8-lesson-3',
      order: 3,
      title: 'Update a record',
      shortTitle: 'Change one field',
      summary: 'A named field can be updated while the other information stays the same.',
      learningGoal: 'Change one dictionary field by assigning a new value through its key.',
      conceptTags: ['dictionary', 'mutation', 'state'],
      steps: [
        {
          id: 'change-one-field',
          content: [
            { type: 'paragraph', text: 'Assign through the key to update one part of the record.' },
            { type: 'example', code: 'student["score"] = 91' },
          ],
          activity: {
            id: 'update-the-score-field',
            kind: 'code',
            title: 'Give the student a new score',
            prompt: 'Change the score field to 91, then print it. Leave the name and age alone.',
            required: true,
            starterCode: 'student = {"name": "Mia", "age": 12, "score": 88}\nstudent["score"] = 88\nprint(student["score"])',
            assessment: {
              kind: 'behavior',
              cases: [{ inputs: [], output: { mode: 'exact', lines: ['91'] } }],
              requirements: ['dictionary-field-update', 'dictionary-field-read'],
            },
            hints: ['Update the score using student["score"] = ...', 'Set it to 91, then print student["score"].'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-8-lesson-4',
      order: 4,
      title: 'Many structured things',
      shortTitle: 'A list of records',
      summary: 'A list can hold one dictionary for each person or thing.',
      learningGoal: 'Create a list of dictionaries and loop through the records to read a named field.',
      conceptTags: ['dictionary', 'list', 'iteration', 'records'],
      steps: [
        {
          id: 'loop-through-students',
          content: [
            { type: 'paragraph', text: 'Use a list for many students, with one small dictionary for each student.' },
            { type: 'example', code: 'students = [\n    {"name": "Mia", "score": 88},\n    {"name": "Leo", "score": 72},\n    {"name": "Ava", "score": 95}\n]\nfor student in students:\n    print(student["name"])' },
          ],
          activity: {
            id: 'print-each-student-name',
            kind: 'code',
            title: 'Print every student name',
            prompt: 'Keep the three student records in the list and print each student’s name in a loop.',
            required: true,
            starterCode: 'students = [{"name": "Mia", "score": 88}, {"name": "Leo", "score": 72}, {"name": "Ava", "score": 95}]\nfor student in students:\n    # Print the name in this record\n    pass',
            assessment: {
              kind: 'behavior',
              cases: [{ inputs: [], output: { mode: 'exact', lines: ['Mia', 'Leo', 'Ava'] } }],
              requirements: ['list-of-records', 'record-iteration'],
            },
            hints: ['Use a for loop to visit each dictionary.', 'Inside the loop, print student["name"].'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-8-lesson-5',
      order: 5,
      title: 'Query structured data',
      shortTitle: 'Find records that match',
      summary: 'A field in each record can be checked to decide which records to show.',
      learningGoal: 'Filter a list of records using a condition on one of their fields.',
      conceptTags: ['dictionary', 'filter', 'condition', 'records'],
      steps: [
        {
          id: 'find-students-over-eighty',
          content: [
            { type: 'paragraph', text: 'Loop through the students, check each score, and show only names that match.' },
            { type: 'example', code: 'for student in students:\n    if student["score"] >= 80:\n        print(student["name"])' },
          ],
          activity: {
            id: 'print-names-of-high-scoring-students',
            kind: 'code',
            title: 'Find the matching students',
            prompt: 'Print the name of every student whose score is 80 or higher.',
            required: true,
            starterCode: 'students = [{"name": "Mia", "score": 88}, {"name": "Leo", "score": 72}, {"name": "Ava", "score": 95}]\nfor student in students:\n    if student["score"] >= 80:\n        # Show the matching name\n        pass',
            assessment: {
              kind: 'behavior',
              cases: [{ inputs: [], output: { mode: 'exact', lines: ['Mia', 'Ava'] } }],
              requirements: ['record-filter'],
            },
            hints: ['Keep the score check inside the loop.', 'Print student["name"] only when student["score"] >= 80.'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-8-lesson-6',
      order: 6,
      title: 'Nested information',
      shortTitle: 'A list inside a record',
      summary: 'A dictionary value can itself be a list.',
      learningGoal: 'Recognise and access a list stored as a dictionary field.',
      conceptTags: ['dictionary', 'list', 'nested-data', 'trace'],
      steps: [
        {
          id: 'predict-the-shape-of-scores',
          content: [
            { type: 'paragraph', text: 'A player has a name and a list of scores. Follow the real Python state to see the shape of scores.' },
            { type: 'example', code: 'player = {"name": "Nova", "scores": [8, 10, 7]}\nscores = player["scores"]' },
          ],
          activity: {
            id: 'predict-player-scores-shape',
            kind: 'choice',
            title: 'What kind of value is scores?',
            prompt: 'The key "scores" points to [8, 10, 7]. What kind of value is that?',
            required: true,
            options: [
              { id: 'text', text: 'Text' },
              { id: 'list', text: 'A list of three numbers' },
              { id: 'dictionary', text: 'A dictionary' },
            ],
            correctOptionId: 'list',
            correctFeedback: 'Right — the square brackets hold a list of three numbers.',
            incorrectFeedback: 'Look at the square brackets around the three score values.',
            hints: ['The key "scores" points to the square-bracketed values.', 'It is a list containing three numbers.'],
          },
        },
        {
          id: 'read-a-score-from-the-record',
          content: [{ type: 'paragraph', text: 'Use the dictionary key first, then the list position.' }],
          activity: {
            id: 'print-the-second-player-score',
            kind: 'code',
            title: 'Read a nested value',
            prompt: 'Print the second score from player. Fix the list position in the starter.',
            required: true,
            starterCode: 'player = {"name": "Nova", "scores": [8, 10, 7]}\nprint(player["scores"][3])',
            assessment: {
              kind: 'behavior',
              cases: [{ inputs: [], output: { mode: 'exact', lines: ['10'] } }],
              requirements: ['dictionary-field-read'],
            },
            hints: ['List positions start at 0.', 'The second score is at position 1.'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-8-lesson-7',
      order: 7,
      title: 'Choose the representation',
      shortTitle: 'Choose a useful shape',
      summary: 'The kind of information and how many things matter when choosing a representation.',
      learningGoal: 'Choose between a single value, list, dictionary, or list of dictionaries for a small scenario.',
      conceptTags: ['representation', 'list', 'dictionary', 'design'],
      steps: [
        {
          id: 'represent-five-temperatures',
          content: [{ type: 'paragraph', text: 'You have five temperatures in order. Which shape fits?' }],
          activity: {
            id: 'choose-temperature-representation',
            kind: 'choice',
            title: 'Represent five temperatures',
            prompt: 'Choose the simplest useful representation.',
            required: true,
            options: representationChoices,
            correctOptionId: 'list',
            correctFeedback: 'Yes — a list is a good fit for several values of the same kind.',
            incorrectFeedback: 'These are several values of the same kind, not fields about one person.',
          },
        },
        {
          id: 'represent-one-person',
          content: [{ type: 'paragraph', text: 'You need one person’s name, age, and email.' }],
          activity: {
            id: 'choose-person-representation',
            kind: 'choice',
            title: 'Represent one person',
            prompt: 'Choose the simplest useful representation.',
            required: true,
            options: representationChoices,
            correctOptionId: 'dictionary',
            correctFeedback: 'Right — a dictionary can name the different fields for one person.',
            incorrectFeedback: 'The person has several different kinds of information, each with its own meaning.',
          },
        },
        {
          id: 'represent-a-class',
          content: [{ type: 'paragraph', text: 'You need to keep information about every student in a class.' }],
          activity: {
            id: 'choose-class-representation',
            kind: 'choice',
            title: 'Represent a class',
            prompt: 'Choose the simplest useful representation.',
            required: true,
            options: representationChoices,
            correctOptionId: 'list-of-records',
            correctFeedback: 'Exactly — use one dictionary per student, then keep those records in a list.',
            incorrectFeedback: 'You have many students, and each student has several named fields.',
          },
        },
        {
          id: 'represent-a-shopping-cart',
          content: [{ type: 'paragraph', text: 'A shopping cart contains several products, each with a name and a quantity.' }],
          activity: {
            id: 'choose-shopping-cart-representation',
            kind: 'choice',
            title: 'Represent a shopping cart',
            prompt: 'Choose the simplest useful representation.',
            required: true,
            options: representationChoices,
            correctOptionId: 'list-of-records',
            correctFeedback: 'Good choice — each product has named fields, and the cart holds many products.',
            incorrectFeedback: 'Each product has multiple fields, and the cart can contain several products.',
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-8-lesson-8',
      order: 8,
      title: 'Build: leaderboard',
      shortTitle: 'Build a leaderboard',
      summary: 'Combine records, loops, conditions, totals, and the best-so-far pattern.',
      learningGoal: 'Use structured records to show players, find the leader, count high scores, and calculate an average.',
      conceptTags: ['project', 'dictionary', 'list', 'algorithm', 'integration'],
      steps: [
        {
          id: 'show-every-player',
          content: [
            { type: 'paragraph', text: 'Start by showing every player and their score.' },
            { type: 'example', code: 'for player in players:\n    print(player["name"], player["score"])' },
          ],
          activity: {
            id: 'leaderboard-show-players',
            kind: 'code',
            title: 'Show every player',
            prompt: 'Loop through players and print each name and score on one line.',
            required: true,
            starterCode: `${leaderboardPlayers}\nfor player in players:\n    # Show this player\n    pass`,
            assessment: {
              kind: 'behavior',
              cases: [{ inputs: [], output: { mode: 'exact', lines: ['Nova 84', 'Pixel 93', 'Echo 76'] } }],
              requirements: ['list-of-records', 'record-iteration'],
            },
            hints: ['Use one loop for every player.', 'Print player["name"] and player["score"].'],
          },
        },
        {
          id: 'find-the-leader',
          content: [{ type: 'paragraph', text: 'Keep the best player seen so far, comparing the score field each time.' }],
          activity: {
            id: 'leaderboard-find-highest-scorer',
            kind: 'code',
            title: 'Find the highest scorer',
            prompt: 'Use a best-so-far loop and print the name of the player with the highest score.',
            required: true,
            starterCode: `${leaderboardPlayers}\nbest = players[0]\nfor player in players:\n    if player["score"] > best["score"]:\n        # Keep this player as best\n        pass\nprint(best["name"])`,
            assessment: {
              kind: 'behavior',
              cases: [{ inputs: [], output: { mode: 'exact', lines: ['Pixel'] } }],
              requirements: ['best-so-far'],
            },
            hints: ['Start best with players[0].', 'Inside the if, assign best = player.'],
          },
        },
        {
          id: 'count-the-high-scores',
          content: [{ type: 'paragraph', text: 'Count how many player records have a score over 80.' }],
          activity: {
            id: 'leaderboard-count-over-eighty',
            kind: 'code',
            title: 'Count high scores',
            prompt: 'Count the players whose score is greater than 80, then print the count.',
            required: true,
            starterCode: `${leaderboardPlayers}\ncount = 0\nfor player in players:\n    if player["score"] > 80:\n        # Increase count by 1\n        pass\nprint(count)`,
            assessment: {
              kind: 'behavior',
              cases: [{ inputs: [], output: { mode: 'exact', lines: ['2'] } }],
              requirements: ['count-if'],
            },
            hints: ['Start count at 0 before the loop.', 'Inside the if, add 1 to count.'],
          },
        },
        {
          id: 'calculate-the-average-score',
          content: [{ type: 'paragraph', text: 'Finish by adding each score field to a total, then divide by the number of players.' }],
          activity: {
            id: 'leaderboard-average-score',
            kind: 'code',
            title: 'Calculate the average score',
            prompt: 'Add every score field to total, divide by the number of players, and print the average.',
            required: true,
            starterCode: `${leaderboardPlayers}\ntotal = 0\nfor player in players:\n    # Add this player's score\n    pass\naverage = total / len(players)\nprint(average)`,
            assessment: {
              kind: 'behavior',
              cases: [{ inputs: [], output: { mode: 'contains', values: ['84.333333'] } }],
              requirements: ['record-total'],
            },
            hints: ['The field containing the score is player["score"].', 'Add player["score"] to total inside the loop.'],
          },
        },
      ],
      status: 'ready',
    },
  ],
}
