import type { Stage } from '../types'

export const stageOne: Stage = {
  id: 'stage-1',
  order: 1,
  title: 'Values and Expressions',
  description: 'Compare text and numbers, then explore how expressions produce values.',
  lessons: [
    {
      id: 'stage-1-lesson-1',
      order: 1,
      title: 'Values',
      shortTitle: 'Values',
      summary: 'A number and text can look related while still being different values.',
      learningGoal: 'Notice the difference between a number and text without memorising type names.',
      conceptTags: ['values', 'numbers', 'text'],
      misconceptions: ['The number 7 and the text "seven" are the same because they mean the same thing.'],
      steps: [
        {
          id: 'see-two-values',
          content: [
            { type: 'paragraph', text: 'Python can work with numbers and with text. Look closely at what is inside the quotation marks.' },
            { type: 'example', code: 'print(7)\nprint("seven")' },
          ],
          activity: {
            id: 'predict-number-and-text',
            kind: 'predict-output',
            title: 'Predict the two lines',
            prompt: 'What will Python display, from the first line to the second?',
            required: true,
            code: 'print(7)\nprint("seven")',
            expectedOutput: ['7', 'seven'],
            hints: ['The first value has no quotation marks.', 'The second value is text inside quotation marks.'],
          },
        },
        {
          id: 'compare-the-values',
          content: [{ type: 'paragraph', text: 'The output gives us a clue. Are these two values the same kind of thing?' }],
          activity: {
            id: 'number-or-text',
            kind: 'choice',
            title: 'Compare them',
            prompt: 'Are 7 and "seven" the same kind of value?',
            required: true,
            options: [
              { id: 'same', text: 'Yes. They mean the same thing.' },
              { id: 'different', text: 'No. One is a number; one is text.' },
            ],
            correctOptionId: 'different',
            correctFeedback: 'Right — 7 is a number, while "seven" is text.',
            incorrectFeedback: 'Look again at the quotation marks: they tell Python this value is text.',
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-1-lesson-2',
      order: 2,
      title: 'The computer can calculate',
      shortTitle: 'Calculations',
      summary: 'Python can calculate with numbers using familiar arithmetic signs.',
      learningGoal: 'Predict and create results using addition, subtraction, and multiplication.',
      conceptTags: ['values', 'arithmetic', 'expressions'],
      steps: [
        {
          id: 'predict-calculations',
          content: [
            { type: 'paragraph', text: 'Python can work out a calculation before it displays the answer.' },
            { type: 'example', code: 'print(4 + 3)\nprint(10 - 2)\nprint(6 * 5)' },
          ],
          activity: {
            id: 'predict-three-calculations',
            kind: 'predict-output',
            title: 'Predict the answers',
            prompt: 'Write the three answers on separate lines, then ask Python to check.',
            required: true,
            code: 'print(4 + 3)\nprint(10 - 2)\nprint(6 * 5)',
            expectedOutput: ['7', '8', '30'],
            hints: ['+ adds.', '− takes away.', '* multiplies.'],
          },
        },
        {
          id: 'make-calculations-work',
          content: [{ type: 'paragraph', text: 'Change the numbers in each calculation until they make the three target answers.' }],
          activity: {
            id: 'edit-three-calculations',
            kind: 'code',
            title: 'Make the calculations work',
            prompt: 'Edit the numbers so the answers are 7, then 8, then 30.',
            required: true,
            starterCode: 'print(1 + 1)\nprint(10 - 1)\nprint(6 * 4)',
            assessment: { kind: 'output', expectation: { mode: 'exact', lines: ['7', '8', '30'] } },
            hints: ['Keep the +, −, and * signs; change the numbers.', 'For example, 4 + 3 makes 7.'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-1-lesson-3',
      order: 3,
      title: 'Expressions collapse into values',
      shortTitle: 'Expressions',
      summary: 'An expression is code that produces a value.',
      learningGoal: 'See an expression reduce to one value and use the word expression.',
      conceptTags: ['expressions', 'evaluation', 'multiplication'],
      steps: [
        {
          id: 'watch-an-expression-collapse',
          content: [
            { type: 'paragraph', text: 'Python works out the multiplication first, then adds 2. Each step becomes a simpler value.' },
            { type: 'evaluation', expression: '2 + 3 * 4', steps: ['2 + 12', '14'], caption: 'Watch the expression reduce' },
          ],
          activity: {
            id: 'predict-expression-result',
            kind: 'predict-output',
            title: 'Predict the final value',
            prompt: 'What single value will this expression produce?',
            required: true,
            code: 'print(2 + 3 * 4)',
            expectedOutput: ['14'],
            hints: ['Work out 3 * 4 first.', 'Then add 2.'],
          },
        },
        {
          id: 'make-an-expression-for-twenty',
          content: [{ type: 'paragraph', text: 'Now change the expression so it produces a different value: 20.' }],
          activity: {
            id: 'create-an-expression-for-twenty',
            kind: 'code',
            title: 'Make a value with an expression',
            prompt: 'Edit the code so Python prints 20.',
            required: true,
            starterCode: 'print(2 + 3 * 4)',
            assessment: { kind: 'output', expectation: { mode: 'exact', lines: ['20'] } },
            hints: ['You can change the numbers or the operations.', 'For example, 4 * 5 produces 20.'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-1-lesson-4',
      order: 4,
      title: 'Expressions can contain expressions',
      shortTitle: 'Parentheses',
      summary: 'Parentheses choose which part of a calculation happens first.',
      learningGoal: 'Use parentheses to make evaluation order visible and predict its effect.',
      conceptTags: ['expressions', 'parentheses', 'evaluation-order'],
      steps: [
        {
          id: 'predict-parentheses',
          content: [
            { type: 'paragraph', text: 'Parentheses make Python work out that part first.' },
            { type: 'example', code: 'print((10 + 2) * 3)\nprint(10 + (2 * 3))' },
            { type: 'callout', tone: 'tip', text: 'Before you run it, point to the part Python will work out first in each line.' },
          ],
          activity: {
            id: 'predict-two-parenthesized-expressions',
            kind: 'predict-output',
            title: 'Predict both results',
            prompt: 'What will the first line print? What about the second?',
            required: true,
            code: 'print((10 + 2) * 3)\nprint(10 + (2 * 3))',
            expectedOutput: ['36', '16'],
            hints: ['The parentheses are different in each line.', 'First calculate the operation inside the parentheses.'],
          },
        },
        {
          id: 'change-which-part-happens-first',
          content: [{ type: 'paragraph', text: 'Change the parentheses so the two lines produce different answers.' }],
          activity: {
            id: 'make-parentheses-change-the-result',
            kind: 'code',
            title: 'Move the parentheses',
            prompt: 'Make these two lines print different answers by changing where the parentheses are.',
            required: true,
            starterCode: 'print((10 + 2) * 3)\nprint((10 + 2) * 3)',
            assessment: { kind: 'output', expectation: { mode: 'distinct-lines', count: 2 } },
            hints: ['Try putting the parentheses around different parts of the second calculation.', 'Compare (10 + 2) * 3 with 10 + (2 * 3).'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-1-lesson-5',
      order: 5,
      title: 'Text can be manipulated too',
      shortTitle: 'Working with text',
      summary: 'Some operations join or repeat text instead of calculating with numbers.',
      learningGoal: 'Predict how joining and repeating text differ from number arithmetic.',
      conceptTags: ['text', 'values', 'operators'],
      steps: [
        {
          id: 'predict-text-operations',
          content: [
            { type: 'paragraph', text: 'The + and * signs can work with text too. What they do depends on the values around them.' },
            { type: 'example', code: 'print("ha" + "ha")\nprint("ha" * 3)' },
          ],
          activity: {
            id: 'predict-joined-and-repeated-text',
            kind: 'predict-output',
            title: 'Predict what the text does',
            prompt: 'What two lines will Python display?',
            required: true,
            code: 'print("ha" + "ha")\nprint("ha" * 3)',
            expectedOutput: ['haha', 'hahaha'],
            hints: ['With text, + joins the pieces.', 'Multiplying text repeats it.'],
          },
        },
        {
          id: 'predict-text-versus-number',
          content: [
            { type: 'paragraph', text: 'Here is a surprising one: both values look like the number five, but they are text inside quotation marks.' },
            { type: 'example', code: 'print("5" + "2")' },
          ],
          activity: {
            id: 'predict-joining-digit-text',
            kind: 'predict-output',
            title: 'A small surprise',
            prompt: 'Will Python calculate seven, or join the two pieces of text?',
            required: true,
            code: 'print("5" + "2")',
            expectedOutput: ['52'],
            hints: ['Look at the quotation marks.', 'This + joins text; it does not add these values as numbers.'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-1-lesson-6',
      order: 6,
      title: 'Different values allow different operations',
      shortTitle: 'Different operations',
      summary: 'A number and text that looks like a number are not interchangeable.',
      learningGoal: 'Use a TypeError as evidence that an operation does not fit those values.',
      conceptTags: ['values', 'types', 'errors'],
      misconceptions: ['The text "5" can be added to the number 2 in the same way as the number 5.'],
      steps: [{
        id: 'notice-the-type-error',
        content: [
          { type: 'paragraph', text: 'Run this code and read Python’s message. The error is the thing to notice here.' },
          { type: 'example', code: 'print("5" + 2)' },
          { type: 'callout', tone: 'note', text: '"5" is text, while 2 is a number. Python calls these different types of value, and + cannot join this pair.' },
        ],
        activity: {
          id: 'observe-mixed-value-type-error',
          kind: 'code',
          title: 'Read Python’s clue',
          prompt: 'Run the example. Look for the TypeError and notice which two values Python could not add.',
          required: true,
          starterCode: 'print("5" + 2)',
          assessment: { kind: 'runtime-error', exceptionName: 'TypeError' },
        },
      }],
      status: 'ready',
    },
    {
      id: 'stage-1-lesson-7',
      order: 7,
      title: 'Functions as black boxes',
      shortTitle: 'Functions as tools',
      summary: 'Use a function by noticing what goes in and what comes out.',
      learningGoal: 'Reason about a function from its input and output without learning its internals.',
      conceptTags: ['functions', 'abstraction', 'values'],
      steps: [
        {
          id: 'meet-len',
          content: [
            { type: 'paragraph', text: 'You have already used print(). Here is another function, len(). Give it some text and it produces the number of characters.' },
            { type: 'example', code: 'print(len("elephant"))' },
            { type: 'callout', tone: 'tip', text: 'We can use a tool by understanding what goes in and what comes out, without knowing how it works inside.' },
          ],
          activity: {
            id: 'predict-length-of-word',
            kind: 'predict-output',
            title: 'Predict the output',
            prompt: 'How many characters are in elephant?',
            required: true,
            code: 'print(len("elephant"))',
            expectedOutput: ['8'],
            hints: ['Count the letters in elephant.', 'len() produces a number.'],
          },
        },
        {
          id: 'use-len-with-new-text',
          content: [{ type: 'paragraph', text: 'Now send a different word into len() and see what comes out.' }],
          activity: {
            id: 'find-length-of-python',
            kind: 'code',
            title: 'Try the same tool with new text',
            prompt: 'Change the word so Python prints the number of letters in Python.',
            required: true,
            starterCode: 'print(len("elephant"))',
            assessment: { kind: 'output', expectation: { mode: 'exact', lines: ['6'] } },
            hints: ['Change only the word inside the quotation marks.', 'Python has six letters.'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-1-lesson-8',
      order: 8,
      title: 'Expression mini-challenge',
      shortTitle: 'Seconds challenge',
      summary: 'Combine multiplication and addition to calculate times in seconds.',
      learningGoal: 'Create useful arithmetic expressions without being given the exact syntax.',
      conceptTags: ['expressions', 'arithmetic', 'problem-solving'],
      steps: [
        {
          id: 'three-minutes-in-seconds',
          content: [
            { type: 'paragraph', text: 'Create an expression to calculate how many seconds are in 3 minutes. Think about how many seconds are in one minute.' },
          ],
          activity: {
            id: 'calculate-three-minutes',
            kind: 'code',
            title: 'Three minutes',
            prompt: 'Write an expression that prints the number of seconds in 3 minutes.',
            required: true,
            starterCode: 'print(0)',
            assessment: { kind: 'output', expectation: { mode: 'exact', lines: ['180'] } },
            hints: ['There are 60 seconds in one minute.', 'Multiply 3 by 60.'],
          },
        },
        {
          id: 'two-hours-in-seconds',
          content: [{ type: 'paragraph', text: 'Now calculate how many seconds are in 2 hours.' }],
          activity: {
            id: 'calculate-two-hours',
            kind: 'code',
            title: 'Two hours',
            prompt: 'Write an expression that prints the number of seconds in 2 hours.',
            required: true,
            starterCode: 'print(0)',
            assessment: { kind: 'output', expectation: { mode: 'exact', lines: ['7200'] } },
            hints: ['There are 60 minutes in one hour and 60 seconds in one minute.', 'Multiply 2 by 60, then by 60 again.'],
          },
        },
        {
          id: 'two-hours-fifteen-minutes-in-seconds',
          content: [{ type: 'paragraph', text: 'Last one: how many seconds are in 2 hours and 15 minutes?' }],
          activity: {
            id: 'calculate-two-hours-fifteen-minutes',
            kind: 'code',
            title: 'Two hours and fifteen minutes',
            prompt: 'Combine the hours and minutes to print the total number of seconds.',
            required: true,
            starterCode: 'print(0)',
            assessment: { kind: 'output', expectation: { mode: 'exact', lines: ['8100'] } },
            hints: ['Calculate the seconds in 2 hours and the seconds in 15 minutes.', 'Add 2 * 60 * 60 and 15 * 60.'],
          },
        },
      ],
      status: 'ready',
    },
  ],
}
