import type { Stage } from '../types'

export const stageZero: Stage = {
  id: 'stage-0',
  order: 0,
  title: 'The Computer Follows Instructions',
  description: 'Run precise instructions and notice what changes.',
  lessons: [
    {
      id: 'saying-something',
      order: 1,
      title: 'Make something happen',
      shortTitle: 'Make something happen',
      summary: 'This line is an instruction.',
      learningGoal: 'Discover that written instructions can cause observable behaviour.',
      conceptTags: ['execution', 'output', 'sequence'],
      steps: [{
        id: 'make-python-speak',
        content: [
          { type: 'paragraph', text: 'Run this line and notice what happens.' },
          { type: 'callout', tone: 'tip', text: 'This line is an instruction.' },
          { type: 'example', code: 'print("Hello!")' },
        ],
        activity: {
          id: 'print-a-greeting',
          kind: 'code',
          title: 'Change the message',
          prompt: 'Change "Hello!" to something else, then run it.',
          required: true,
          starterCode: 'print("Hello!")',
          hints: ['Change only the words between the quotation marks.', 'Run it again and look at the output.'],
          assessment: {
            kind: 'output',
            expectation: { mode: 'non-empty' },
            rejectExact: ['Hello!'],
          },
        },
      }],
      status: 'ready',
    },
    {
      id: 'instructions-in-order',
      order: 2,
      title: 'Instructions happen in order',
      shortTitle: 'Instructions in order',
      summary: 'The computer follows one instruction after another.',
      learningGoal: 'Predict and arrange a simple sequence of instructions.',
      conceptTags: ['sequence', 'execution'],
      steps: [
        {
          id: 'predict-the-order',
          content: [
            { type: 'paragraph', text: 'Read the lines from top to bottom. What order will the messages appear in?' },
            { type: 'example', code: 'print("First")\nprint("Second")\nprint("Third")' },
          ],
          activity: {
            id: 'predict-message-order',
            kind: 'predict-output',
            title: 'Predict the output',
            prompt: 'Write the three messages in the order you think they will appear.',
            required: true,
            code: 'print("First")\nprint("Second")\nprint("Third")',
            expectedOutput: ['First', 'Second', 'Third'],
          },
        },
        {
          id: 'arrange-the-instructions',
          content: [
            { type: 'paragraph', text: 'Now put the instructions in an order that makes the messages appear first, second, and third.' },
          ],
          activity: {
            id: 'put-instructions-in-order',
            kind: 'arrange-code',
            title: 'Arrange the lines',
            prompt: 'Move each line until the output will say First, then Second, then Third.',
            required: true,
            fragments: [
              { id: 'first', code: 'print("First")' },
              { id: 'second', code: 'print("Second")' },
              { id: 'third', code: 'print("Third")' },
            ],
            startingOrder: ['third', 'first', 'second'],
            correctOrder: ['first', 'second', 'third'],
            hints: ['The first message needs to be on the first line.'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'one-change-one-consequence',
      order: 3,
      title: 'One change → one consequence',
      shortTitle: 'One change at a time',
      summary: 'Change one thing, run again, and observe what changed.',
      learningGoal: 'Use a small experiment to connect one code change to its result.',
      conceptTags: ['experimentation', 'debugging', 'output'],
      steps: [
        {
          id: 'change-one-thing',
          content: [
            { type: 'paragraph', text: 'Try changing a word, adding or removing a line, or moving a line. Change one thing at a time.' },
            { type: 'callout', tone: 'tip', text: 'Run the program again and compare what changed.' },
            { type: 'example', code: 'print("Ready")\nprint("Go!")' },
          ],
          activity: {
            id: 'experiment-with-output',
            kind: 'code',
            title: 'Run a small experiment',
            prompt: 'Change, add, remove, or move an instruction. Run it and notice the consequence.',
            required: true,
            starterCode: 'print("Ready")\nprint("Go!")',
            assessment: {
              kind: 'output',
              expectation: { mode: 'non-empty' },
              rejectExact: ['Ready\nGo!'],
            },
            hints: ['Change just one line first.', 'Run it and compare the output with the example.'],
          },
        },
        {
          id: 'notice-the-consequence',
          content: [
            { type: 'paragraph', text: 'A small change makes it easier to see why the result changed.' },
          ],
          activity: {
            id: 'reflect-on-the-experiment',
            kind: 'reflection',
            title: 'What did you notice?',
            prompt: 'What one thing did you change, and what happened when you ran it?',
            required: false,
            placeholder: 'A short note for yourself…',
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'computers-are-literal',
      order: 4,
      title: 'Computers are extremely literal',
      shortTitle: 'Read the clue',
      summary: 'A message from Python can help us repair an instruction.',
      learningGoal: 'Treat a syntax error as useful information and repair a tiny mistake.',
      conceptTags: ['syntax', 'errors', 'debugging'],
      misconceptions: ['An error means the learner failed.'],
      steps: [{
        id: 'repair-the-quotation-mark',
        content: [
          { type: 'paragraph', text: 'This instruction is missing something. Run it and read the clue Python gives you.' },
          { type: 'callout', tone: 'note', text: 'Python tried to understand the instruction but could not. Its message gives us a clue.' },
          { type: 'example', code: 'print("Hello)' },
        ],
        activity: {
          id: 'repair-a-missing-quote',
          kind: 'code',
          title: 'Repair the instruction',
          prompt: 'Fix the missing quotation mark so the program prints Hello.',
          required: true,
          starterCode: 'print("Hello)',
          assessment: { kind: 'output', expectation: { mode: 'exact', lines: ['Hello'] } },
          hints: ['Text needs an opening and a closing quotation mark.', 'Add a quotation mark just before the closing parenthesis.'],
        },
      }],
      status: 'ready',
    },
    {
      id: 'trace-the-execution-pointer',
      order: 5,
      title: 'Trace the execution pointer',
      shortTitle: 'Follow each instruction',
      summary: 'Watch which line runs next.',
      learningGoal: 'Observe a real program execute one instruction after another.',
      conceptTags: ['execution', 'sequence', 'tracing'],
      steps: [{
        id: 'step-through-lines',
        content: [
          { type: 'paragraph', text: 'Follow the marker as the program runs. It moves to the instruction Python is carrying out.' },
          { type: 'example', code: 'print("A")\nprint("B")\nprint("C")' },
        ],
        activity: {
          id: 'trace-three-instructions',
          kind: 'trace',
          title: 'Step through the program',
          prompt: 'Run the program, then move through each recorded instruction.',
          required: true,
          code: 'print("A")\nprint("B")\nprint("C")',
        },
      }],
      status: 'ready',
    },
    {
      id: 'first-tiny-creation',
      order: 6,
      title: 'First tiny creation',
      shortTitle: 'Make it yours',
      summary: 'Create a three-line introduction for an imaginary character.',
      learningGoal: 'Combine simple output instructions into a small program of your own.',
      conceptTags: ['creation', 'sequence', 'output'],
      steps: [{
        id: 'introduce-a-character',
        content: [
          { type: 'paragraph', text: 'Make the computer introduce an imaginary character in exactly three lines.' },
          { type: 'callout', tone: 'tip', text: 'Choose any character and details you like. There is no single right answer.' },
          { type: 'example', code: 'My name is Byte.\nI live on Mars.\nI love pancakes.' },
        ],
        activity: {
          id: 'write-a-three-line-introduction',
          kind: 'code',
          title: 'Create your program',
          prompt: 'Use three print() instructions to introduce an imaginary character in exactly three lines.',
          required: true,
          starterCode: 'print("")\nprint("")\nprint("")',
          assessment: { kind: 'output', expectation: { mode: 'line-count', count: 3 } },
          hints: [
            'Use one print() instruction for each line.',
            'Put a short sentence inside the quotation marks on each line.',
            'Run the program and check that the output has exactly three lines.',
          ],
        },
      }],
      status: 'ready',
    },
  ],
}
