import type { Stage } from '../types'

export const stageFour: Stage = {
  id: 'stage-4',
  order: 4,
  title: 'Repetition and Time',
  description: 'Repeat instructions and watch values change over time.',
  lessons: [
    {
      id: 'stage-4-lesson-1',
      order: 1,
      title: 'Discover the repetition problem',
      shortTitle: 'Too many repeated lines',
      summary: 'Copying an instruction works, but becomes awkward when we need many repetitions.',
      learningGoal: 'Experience why repeating a long instruction by copying does not scale.',
      conceptTags: ['repetition', 'motivation', 'output'],
      steps: [{
        id: 'add-one-more-jump',
        content: [
          { type: 'paragraph', text: 'These lines work. But what if we needed 100 jumps?' },
          { type: 'example', code: 'print("Jump!")\nprint("Jump!")\nprint("Jump!")\nprint("Jump!")\nprint("Jump!")' },
          { type: 'callout', tone: 'tip', text: 'For this first try, solve it by adding another instruction. We will learn a shorter way next.' },
        ],
        activity: {
          id: 'write-six-jumps',
          kind: 'code',
          title: 'Make six jumps',
          prompt: 'Add one more print instruction so Python displays Jump! exactly six times.',
          required: true,
          starterCode: 'print("Jump!")\nprint("Jump!")\nprint("Jump!")\nprint("Jump!")\nprint("Jump!")',
          assessment: { kind: 'output', expectation: { mode: 'line-count', count: 6 } },
          hints: ['Each print() makes one line.', 'Add one more print("Jump!") instruction.'],
        },
      }],
      status: 'ready',
    },
    {
      id: 'stage-4-lesson-2',
      order: 2,
      title: 'Repeat something a fixed number of times',
      shortTitle: 'Repeat with for',
      summary: 'A for loop repeats its indented instructions a chosen number of times.',
      learningGoal: 'Use for and range() to repeat an instruction a fixed number of times.',
      conceptTags: ['for', 'range', 'repetition'],
      steps: [{
        id: 'repeat-with-range',
        content: [
          { type: 'paragraph', text: 'A for loop can repeat an indented instruction. range(5) gives it five turns.' },
          { type: 'example', code: 'for number in range(5):\n    print("Jump!")' },
          { type: 'callout', tone: 'note', text: 'The colon starts the repeated block. Indentation shows which instruction belongs to it.' },
        ],
        activity: {
          id: 'repeat-five-jumps',
          kind: 'code',
          title: 'Repeat five times',
          prompt: 'Run the loop and notice that the indented instruction happens five times.',
          required: true,
          starterCode: 'for number in range(5):\n    print("Jump!")',
          assessment: {
            kind: 'output-and-ast',
            expectation: { mode: 'line-count', count: 5 },
            requirement: 'for-loop',
          },
          hints: ['The repeated instruction is indented under for.', 'range(5) chooses five turns.'],
        },
      }],
      status: 'ready',
    },
    {
      id: 'stage-4-lesson-3',
      order: 3,
      title: 'The loop variable changes',
      shortTitle: 'Follow each turn',
      summary: 'The loop name receives a new value on each repetition.',
      learningGoal: 'Trace the changing loop variable and notice where range stops.',
      conceptTags: ['for', 'range', 'loop-variable', 'sequence'],
      steps: [
        {
          id: 'predict-the-loop-values',
          content: [
            { type: 'paragraph', text: 'Each time around, number gets the next value from range(5).' },
            { type: 'example', code: 'for number in range(5):\n    print(number)' },
          ],
          activity: {
            id: 'predict-five-loop-values',
            kind: 'predict-output',
            title: 'Predict each turn',
            prompt: 'Write the values of number in the order Python will print them.',
            required: true,
            code: 'for number in range(5):\n    print(number)',
            expectedOutput: ['0', '1', '2', '3', '4'],
            hints: ['The first value is 0.', 'range(5) stops before 5.'],
          },
        },
        {
          id: 'notice-where-range-stops',
          content: [{ type: 'paragraph', text: 'range(5) starts at 0 and gives five values: 0 through 4.' }],
          activity: {
            id: 'explain-range-stop',
            kind: 'choice',
            title: 'Why is 5 not printed?',
            prompt: 'Why does range(5) finish after number is 4?',
            required: true,
            options: [
              { id: 'stops-before-five', text: 'It starts at 0 and stops before 5.' },
              { id: 'loop-skips-five', text: 'The loop skips 5 by accident.' },
            ],
            correctOptionId: 'stops-before-five',
            correctFeedback: 'Right — five values starting at 0 are 0, 1, 2, 3, and 4.',
            incorrectFeedback: 'range(5) gives five values, starting at 0, and stops before 5.',
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-4-lesson-4',
      order: 4,
      title: 'Use the changing value',
      shortTitle: 'Calculate each turn',
      summary: 'Use the current loop value to calculate a different result each time.',
      learningGoal: 'Use a changing loop value inside a calculation.',
      conceptTags: ['for', 'range', 'arithmetic'],
      steps: [
        {
          id: 'predict-doubled-values',
          content: [
            { type: 'paragraph', text: 'The loop value can be part of a calculation. Python works it out on every turn.' },
            { type: 'example', code: 'for number in range(5):\n    print(number * 2)' },
          ],
          activity: {
            id: 'predict-doubled-loop-values',
            kind: 'predict-output',
            title: 'Predict the calculations',
            prompt: 'What will number * 2 print on each turn?',
            required: true,
            code: 'for number in range(5):\n    print(number * 2)',
            expectedOutput: ['0', '2', '4', '6', '8'],
            hints: ['The loop values are 0, 1, 2, 3, and 4.', 'Multiply each of those values by 2.'],
          },
        },
        {
          id: 'make-multiples-of-three',
          content: [{ type: 'paragraph', text: 'Change the calculation so each turn makes the next multiple of 3.' }],
          activity: {
            id: 'print-five-multiples-of-three',
            kind: 'code',
            title: 'Make multiples of three',
            prompt: 'Print 0, 3, 6, 9, and 12 using the loop value.',
            required: true,
            starterCode: 'for number in range(5):\n    print(number * 2)',
            assessment: {
              kind: 'output-and-ast',
              expectation: { mode: 'exact', lines: ['0', '3', '6', '9', '12'] },
              requirement: 'range-call',
            },
            hints: ['Keep the loop value; change the calculation inside print().', 'Multiply number by 3.'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-4-lesson-5',
      order: 5,
      title: 'State can survive between iterations',
      shortTitle: 'Keep a running total',
      summary: 'A value can carry information from one repetition into the next.',
      learningGoal: 'Step through and record how a running total changes during a loop.',
      conceptTags: ['state', 'for', 'repetition', 'accumulation'],
      steps: [
        {
          id: 'step-through-the-total',
          content: [
            { type: 'paragraph', text: 'total starts at 0. Each turn adds 2 to the value it already holds.' },
            { type: 'example', code: 'total = 0\nfor number in range(4):\n    total = total + 2\n    print(total)' },
            { type: 'callout', tone: 'tip', text: 'Follow total after every pass: it is remembered between repetitions.' },
          ],
          activity: {
            id: 'step-through-running-total',
            kind: 'trace',
            title: 'Step through the changing state',
            prompt: 'Run the loop and follow total as Python repeats the instructions.',
            required: true,
            code: 'total = 0\nfor number in range(4):\n    total = total + 2\n    print(total)',
          },
        },
        {
          id: 'fill-the-total-table',
          content: [{ type: 'paragraph', text: 'Now record the total after each repetition. Each row is another visit to the same code line.' }],
          activity: {
            id: 'record-four-running-totals',
            kind: 'trace-table',
            title: 'Record each turn',
            prompt: 'Enter total after each time line 3 runs, then compare your table with Python.',
            required: true,
            code: 'total = 0\nfor number in range(4):\n    total = total + 2\n    print(total)',
            variables: ['total'],
            checkpoints: [
              { id: 'turn-one', line: 3, occurrence: 1, label: 'after turn 1' },
              { id: 'turn-two', line: 3, occurrence: 2, label: 'after turn 2' },
              { id: 'turn-three', line: 3, occurrence: 3, label: 'after turn 3' },
              { id: 'turn-four', line: 3, occurrence: 4, label: 'after turn 4' },
            ],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-4-lesson-6',
      order: 6,
      title: 'Decisions inside repetition',
      shortTitle: 'Loop plus if',
      summary: 'A decision can be checked on every turn of a loop.',
      learningGoal: 'Trace how a loop value and a condition work together.',
      conceptTags: ['for', 'conditional', 'trace'],
      steps: [
        {
          id: 'trace-the-filtered-values',
          content: [
            { type: 'paragraph', text: 'The loop visits each number. The if statement decides whether that turn prints it.' },
            { type: 'example', code: 'for number in range(6):\n    if number > 2:\n        print(number)' },
          ],
          activity: {
            id: 'step-through-loop-and-decision',
            kind: 'trace',
            title: 'Follow the loop and decision',
            prompt: 'Step through each turn. Notice when Python skips the indented print line.',
            required: true,
            code: 'for number in range(6):\n    if number > 2:\n        print(number)',
          },
        },
        {
          id: 'predict-the-values-that-pass',
          content: [{ type: 'paragraph', text: 'Only values greater than 2 make the if question True.' }],
          activity: {
            id: 'predict-filtered-loop-output',
            kind: 'predict-output',
            title: 'Which numbers appear?',
            prompt: 'Write the values printed by the loop, in order.',
            required: true,
            code: 'for number in range(6):\n    if number > 2:\n        print(number)',
            expectedOutput: ['3', '4', '5'],
            hints: ['The loop visits 0 through 5.', 'The first value greater than 2 is 3.'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-4-lesson-7',
      order: 7,
      title: 'Repeat while something remains true',
      shortTitle: 'Repeat with while',
      summary: 'A while loop repeats as long as its condition is True.',
      learningGoal: 'Use a changing value to make a while loop stop.',
      conceptTags: ['while', 'condition', 'state', 'termination'],
      steps: [
        {
          id: 'trace-a-countdown',
          content: [
            { type: 'paragraph', text: 'The loop asks count > 0 before each turn. The body reduces count so the answer eventually becomes False.' },
            { type: 'example', code: 'count = 3\nwhile count > 0:\n    print(count)\n    count = count - 1\nprint("Go!")' },
          ],
          activity: {
            id: 'trace-countdown-loop',
            kind: 'trace',
            title: 'Follow the condition and count',
            prompt: 'Step through the loop. What changes before Python checks count > 0 again?',
            required: true,
            code: 'count = 3\nwhile count > 0:\n    print(count)\n    count = count - 1\nprint("Go!")',
          },
        },
        {
          id: 'choose-what-stops-the-loop',
          content: [{ type: 'paragraph', text: 'The loop stops when its question becomes False.' }],
          activity: {
            id: 'identify-countdown-stop',
            kind: 'choice',
            title: 'What makes it stop?',
            prompt: 'What causes the countdown loop to finish?',
            required: true,
            options: [
              { id: 'condition-false', text: 'count becomes 0, so count > 0 is False.' },
              { id: 'print-stops', text: 'print() stops the loop after one message.' },
            ],
            correctOptionId: 'condition-false',
            correctFeedback: 'Yes — the repeated subtraction eventually makes the condition False.',
            incorrectFeedback: 'print() displays a value but does not end a loop. Watch count change.',
          },
        },
        {
          id: 'create-a-while-countdown',
          content: [{ type: 'paragraph', text: 'Now make a shorter countdown of your own. The condition and changing value must agree.' }],
          activity: {
            id: 'write-a-three-countdown',
            kind: 'code',
            title: 'Make a safe countdown',
            prompt: 'Use while to print 3, 2, 1, then Go! Make the loop condition become False.',
            required: true,
            starterCode: 'count = 3\nwhile count > 0:\n    print(count)\n    count = count - 1\nprint("Go!")',
            assessment: {
              kind: 'behavior',
              requirements: ['while-loop'],
              cases: [{ inputs: [], output: { mode: 'exact', lines: ['3', '2', '1', 'Go!'] } }],
            },
            hints: ['Put count = count - 1 inside the loop.', 'Subtract 1 on every turn so count reaches 0.'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-4-lesson-8',
      order: 8,
      title: 'The infinite loop',
      shortTitle: 'A loop that will not stop',
      summary: 'A loop cannot finish if its condition never becomes False.',
      learningGoal: 'Observe safe timeout recovery and identify the missing state change.',
      conceptTags: ['while', 'infinite-loop', 'timeout', 'debugging'],
      steps: [
        {
          id: 'observe-the-safe-timeout',
          content: [
            { type: 'paragraph', text: 'This loop checks count > 0 but never changes count. Python cannot reach a False answer.' },
            { type: 'example', code: 'count = 3\nwhile count > 0:\n    print(count)' },
            { type: 'callout', tone: 'note', text: 'The learning app will stop a program that runs too long and prepare Python again.' },
          ],
          activity: {
            id: 'run-the-non-stopping-loop',
            kind: 'code',
            title: 'Notice the time limit',
            prompt: 'Run the example. Python will stop it safely because count never changes.',
            required: true,
            starterCode: 'count = 3\nwhile count > 0:\n    print(count)',
            assessment: { kind: 'timeout' },
            hints: ['The condition starts True.', 'Look for an instruction that changes count inside the loop.'],
          },
        },
        {
          id: 'explain-the-never-changing-condition',
          content: [{ type: 'paragraph', text: 'A loop needs a path toward making its condition False.' }],
          activity: {
            id: 'find-why-the-loop-continues',
            kind: 'choice',
            title: 'Why does it keep going?',
            prompt: 'Why can count > 0 never become False in this example?',
            required: true,
            options: [
              { id: 'count-never-changes', text: 'count stays 3 because the loop never changes it.' },
              { id: 'greater-than-always-true', text: '> always means True in a while loop.' },
            ],
            correctOptionId: 'count-never-changes',
            correctFeedback: 'Exactly — count needs to change so the condition can become False.',
            incorrectFeedback: '> is an ordinary comparison. The value stays 3 because no line changes it.',
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-4-lesson-9',
      order: 9,
      title: 'Repeat until the user succeeds',
      shortTitle: 'Try until correct',
      summary: 'A while loop can keep asking until an answer matches.',
      learningGoal: 'Use repeated input and a changing answer to continue until success.',
      conceptTags: ['while', 'input', 'condition', 'repetition'],
      steps: [{
        id: 'keep-asking-for-the-secret-word',
        content: [
          { type: 'paragraph', text: 'The answer starts as empty text, so the loop asks. It keeps asking until the answer is python.' },
          { type: 'example', code: 'answer = ""\nwhile answer != "python":\n    answer = input("Secret word: ")\nprint("Correct!")' },
          { type: 'callout', tone: 'tip', text: 'The answer changes when input() gives the name a new value.' },
        ],
        activity: {
          id: 'build-a-secret-word-check',
          kind: 'code',
          title: 'Keep asking until it is right',
          prompt: 'Ask for the secret word again whenever it is not python. Print Correct! only after a correct answer.',
          required: true,
          starterCode: 'answer = ""\nwhile answer != "python":\n    answer = input("Secret word: ")\nprint("Correct!")',
          sampleInputs: ['python'],
          assessment: {
            kind: 'behavior',
            requirements: ['while-loop'],
            cases: [
              { inputs: ['python'], output: { mode: 'exact', lines: ['Correct!'] }, requiredInputs: [{ inputIndex: 0, mustAppearInOutput: false }] },
              { inputs: ['ruby', 'python'], output: { mode: 'exact', lines: ['Correct!'] }, requiredInputs: [{ inputIndex: 0, mustAppearInOutput: false }, { inputIndex: 1, mustAppearInOutput: false }] },
            ],
          },
          hints: ['Start answer with empty text so the first check asks the question.', 'Use while answer != "python" and assign a new input() answer inside it.'],
        },
      }],
      status: 'ready',
    },
    {
      id: 'stage-4-lesson-10',
      order: 10,
      title: 'Build: launch sequence',
      shortTitle: 'Launch sequence',
      summary: 'Combine a counted loop, a changing number, and a final instruction.',
      learningGoal: 'Build a countdown that can start from a value entered by the user.',
      conceptTags: ['project', 'for', 'range', 'input', 'output'],
      steps: [{
        id: 'build-the-launch-countdown',
        content: [
          { type: 'paragraph', text: 'Make a launch countdown. The start value can change, but the sequence still reaches Launch!' },
          { type: 'list', items: ['Ask where the countdown should start.', 'Use a for loop and range() to count down to 1.', 'Print Launch! after the loop.'] },
          { type: 'example', caption: 'One possible run', code: 'Start? 5\n5\n4\n3\n2\n1\nLaunch!' },
        ],
        activity: {
          id: 'create-launch-sequence',
          kind: 'code',
          title: 'Prepare for launch',
          prompt: 'Ask for a starting number, count down to 1, then print Launch! Test more than one starting number.',
          required: true,
          starterCode: 'start = int(input("Start? "))\nfor number in range(start, 0, -1):\n    print(number)\nprint("Launch!")',
          sampleInputs: ['5'],
          assessment: {
            kind: 'behavior',
            requirements: ['for-loop', 'range-call'],
            cases: [
              { inputs: ['5'], output: { mode: 'exact', lines: ['5', '4', '3', '2', '1', 'Launch!'] }, requiredInputs: [{ inputIndex: 0, mustAppearInOutput: false }] },
              { inputs: ['3'], output: { mode: 'exact', lines: ['3', '2', '1', 'Launch!'] }, requiredInputs: [{ inputIndex: 0, mustAppearInOutput: false }] },
              { inputs: ['1'], output: { mode: 'exact', lines: ['1', 'Launch!'] }, requiredInputs: [{ inputIndex: 0, mustAppearInOutput: false }] },
            ],
          },
          hints: [
            'Convert the start answer with int().',
            'Use range(start, 0, -1) so each turn counts down and stops before 0.',
            'Print Launch! after the loop, with no indentation.',
          ],
        },
      }],
      status: 'ready',
    },
  ],
}
