import type { Stage } from '../types'

const patternChoices = [
  { id: 'total', text: 'Total / accumulate' },
  { id: 'count', text: 'Count items that pass a test' },
  { id: 'average', text: 'Average: total divided by count' },
  { id: 'search', text: 'Search for a match' },
  { id: 'best', text: 'Keep the best value so far' },
  { id: 'transform', text: 'Transform every item' },
  { id: 'filter', text: 'Keep items that pass a test' },
] as const

export const stageSeven: Stage = {
  id: 'stage-7',
  order: 7,
  title: 'Reusable Algorithmic Patterns',
  description: 'Recognise useful shapes for totals, counts, searches, and more.',
  lessons: [
    {
      id: 'stage-7-lesson-1',
      order: 1,
      title: 'Total / accumulate',
      shortTitle: 'Keep a running total',
      summary: 'A total grows as a loop visits each value.',
      learningGoal: 'Build a total by starting at zero and adding each value as the loop runs.',
      conceptTags: ['algorithm', 'total', 'accumulator', 'for'],
      steps: [
        {
          id: 'build-the-total-pattern',
          content: [
            { type: 'paragraph', text: 'A running total carries a result forward as the loop visits each item.' },
            { type: 'list', items: ['Start the accumulator at 0.', 'Visit each value.', 'Add the value to the accumulator.', 'Use the final result.'] },
            { type: 'example', code: 'numbers = [4, 7, 2]\ntotal = 0\nfor number in numbers:\n    total = total + number\nprint(total)' },
          ],
          activity: {
            id: 'add-each-number-to-a-total',
            kind: 'code',
            title: 'Build a running total',
            prompt: 'Start total at 0, add each number in the list, and print the answer.',
            required: true,
            starterCode: 'numbers = [4, 7, 2]\ntotal = 0\nfor number in numbers:\n    # Add number to total\n    pass\n\nprint(total)',
            assessment: {
              kind: 'behavior',
              cases: [{ inputs: [], output: { mode: 'exact', lines: ['13'] } }],
              requirements: ['total-accumulator'],
            },
            hints: ['The update belongs inside the loop.', 'Use total = total + number.'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-7-lesson-2',
      order: 2,
      title: 'Count',
      shortTitle: 'Count what passes',
      summary: 'A count is a total that grows by 1 only when an item passes a test.',
      learningGoal: 'Count the items that meet a condition using a loop, if, and a counter.',
      conceptTags: ['algorithm', 'count', 'conditional', 'for'],
      steps: [
        {
          id: 'count-passing-scores',
          content: [
            { type: 'paragraph', text: 'A count follows the total pattern, but it adds 1 only for items we want to count.' },
            { type: 'example', code: 'scores = [4, 9, 2, 10, 7]\ncount = 0\nfor score in scores:\n    if score >= 7:\n        count = count + 1\nprint(count)' },
            { type: 'callout', tone: 'note', text: 'The count changes for passing scores, not by the score value itself.' },
          ],
          activity: {
            id: 'count-scores-at-least-seven',
            kind: 'code',
            title: 'Count the passing scores',
            prompt: 'Count how many scores are 7 or higher, then print the count.',
            required: true,
            starterCode: 'scores = [4, 9, 2, 10, 7]\ncount = 0\nfor score in scores:\n    if score >= 7:\n        # Increase count by 1\n        pass\n\nprint(count)',
            assessment: {
              kind: 'behavior',
              cases: [{ inputs: [], output: { mode: 'exact', lines: ['3'] } }],
              requirements: ['count-if'],
            },
            hints: ['Keep count = 0 before the loop.', 'Inside the if, use count = count + 1.'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-7-lesson-3',
      order: 3,
      title: 'Average combines patterns',
      shortTitle: 'Combine total and count',
      summary: 'An average combines a total with a count: total divided by count.',
      learningGoal: 'Combine accumulation and counting to find an average.',
      conceptTags: ['algorithm', 'average', 'total', 'count'],
      steps: [
        {
          id: 'notice-total-count-average',
          content: [
            { type: 'paragraph', text: 'An average uses two patterns you already know: add the values, then divide by how many there are.' },
            { type: 'example', code: 'average = total / count', caption: 'Total ÷ number of values.' },
          ],
          activity: {
            id: 'predict-average-pieces',
            kind: 'predict-output',
            title: 'Find the pieces first',
            prompt: 'Predict the total, the number of scores, and their average, in that order.',
            required: true,
            code: 'scores = [4, 9, 2, 10, 7]\ntotal = 0\nfor score in scores:\n    total = total + score\ncount = len(scores)\naverage = total / count\nprint(total)\nprint(count)\nprint(average)',
            expectedOutput: ['32', '5', '6.4'],
          },
        },
        {
          id: 'calculate-an-average',
          content: [{ type: 'paragraph', text: 'Build the known pieces, then divide the total by the count.' }],
          activity: {
            id: 'calculate-score-average',
            kind: 'code',
            title: 'Find the average score',
            prompt: 'Use a running total, count the scores with len(), then print total / count.',
            required: true,
            starterCode: 'scores = [4, 9, 2, 10, 7]\ntotal = 0\nfor score in scores:\n    # Add each score to total\n    pass\n\ncount = len(scores)\naverage = total / count\nprint(average)',
            assessment: {
              kind: 'behavior',
              cases: [{ inputs: [], output: { mode: 'exact', lines: ['6.4'] } }],
              requirements: ['total-accumulator', 'length-call'],
            },
            hints: ['Finish the total loop first.', 'Divide total by count and print average.'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-7-lesson-4',
      order: 4,
      title: 'Search',
      shortTitle: 'Remember a match',
      summary: 'A flag can remember whether a loop found a matching value.',
      learningGoal: 'Search a collection and carry a True/False result forward through the loop.',
      conceptTags: ['algorithm', 'search', 'flag', 'input'],
      steps: [
        {
          id: 'carry-found-through-the-loop',
          content: [
            { type: 'paragraph', text: 'Start found at False. If the loop finds a match, change found to True. It remembers the result after the loop finishes.' },
            { type: 'example', code: 'names = ["Mia", "Leo", "Ava"]\nwanted = "Leo"\nfound = False\nfor name in names:\n    if name == wanted:\n        found = True\nprint(found)' },
          ],
          activity: {
            id: 'search-for-a-name',
            kind: 'code',
            title: 'Search for a name',
            prompt: 'Ask for a name, search the list, then print True if it was found and False if it was not.',
            required: true,
            sampleInputs: ['Leo'],
            starterCode: 'names = ["Mia", "Leo", "Ava"]\nwanted = input("Name to find: ")\nfound = False\nfor name in names:\n    if name == wanted:\n        # Remember that you found it\n        pass\n\nprint(found)',
            assessment: {
              kind: 'behavior',
              cases: [
                { inputs: ['Leo'], output: { mode: 'exact', lines: ['True'] }, requiredInputs: [{ inputIndex: 0, mustAppearInOutput: false }] },
                { inputs: ['Noor'], output: { mode: 'exact', lines: ['False'] }, requiredInputs: [{ inputIndex: 0, mustAppearInOutput: false }] },
              ],
              requirements: ['search-flag'],
            },
            hints: ['Set found = True inside the if when the names match.', 'Keep print(found) after the loop.'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-7-lesson-5',
      order: 5,
      title: 'Best so far',
      shortTitle: 'Keep the best so far',
      summary: 'Start with a real item, then replace it when a better one appears.',
      learningGoal: 'Track a best value through a loop and understand why it starts from the collection.',
      conceptTags: ['algorithm', 'best-so-far', 'maximum', 'for'],
      steps: [
        {
          id: 'watch-best-change',
          content: [
            { type: 'paragraph', text: 'Keep a value called best. When the loop finds a better value, replace best. Start from the first item, not 0.' },
            { type: 'example', code: 'scores = [6, 3, 9, 7]\nbest = scores[0]\nfor score in scores:\n    if score > best:\n        best = score' },
          ],
          activity: {
            id: 'predict-best-at-each-turn',
            kind: 'predict-output',
            title: 'Watch the best value',
            prompt: 'The program prints best after each score. What four values will it print?',
            required: true,
            code: 'scores = [6, 3, 9, 7]\nbest = scores[0]\nfor score in scores:\n    if score > best:\n        best = score\n    print(best)',
            expectedOutput: ['6', '6', '9', '9'],
          },
        },
        {
          id: 'find-a-best-value',
          content: [{ type: 'callout', tone: 'tip', text: 'Try an all-negative list. Starting best at 0 would give an answer that is not in the list.' }],
          activity: {
            id: 'find-the-highest-score',
            kind: 'code',
            title: 'Find the highest score',
            prompt: 'Use the best-so-far pattern to print the highest value in this list.',
            required: true,
            starterCode: 'scores = [-6, -3, -9, -7]\nbest = scores[0]\nfor score in scores:\n    if score > best:\n        # Replace best when score is higher\n        pass\n\nprint(best)',
            assessment: {
              kind: 'behavior',
              cases: [{ inputs: [], output: { mode: 'exact', lines: ['-3'] } }],
              requirements: ['best-so-far'],
            },
            hints: ['Initialize best with scores[0].', 'Inside the if, set best = score.'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-7-lesson-6',
      order: 6,
      title: 'Transform',
      shortTitle: 'Make a changed list',
      summary: 'A transform visits each item and puts a changed version into a new list.',
      learningGoal: 'Create a new collection by transforming every item in the input collection.',
      conceptTags: ['algorithm', 'transform', 'list', 'for'],
      steps: [
        {
          id: 'transform-each-item',
          content: [
            { type: 'paragraph', text: 'A transform keeps every item, but changes each one as it builds a new list.' },
            { type: 'example', code: 'numbers = [1, 2, 3]\ndoubled = []\nfor number in numbers:\n    doubled.append(number * 2)' },
            { type: 'callout', tone: 'note', text: 'Input list → change each item → new output list.' },
          ],
          activity: {
            id: 'double-each-number-into-a-new-list',
            kind: 'code',
            title: 'Transform every number',
            prompt: 'Build a new list containing each number multiplied by 2, then print the new list.',
            required: true,
            starterCode: 'numbers = [1, -2, 3]\ndoubled = []\nfor number in numbers:\n    # Append a changed number\n    pass\n\nprint(doubled)',
            assessment: {
              kind: 'behavior',
              cases: [{ inputs: [], output: { mode: 'exact', lines: ['[2, -4, 6]'] } }],
              requirements: ['transform-list'],
            },
            hints: ['Keep the original list and create a separate empty list.', 'Append number * 2 for each number.'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-7-lesson-7',
      order: 7,
      title: 'Filter',
      shortTitle: 'Keep matching items',
      summary: 'A filter visits every item but keeps only the ones that pass a test.',
      learningGoal: 'Build a new list containing only items that meet a condition.',
      conceptTags: ['algorithm', 'filter', 'conditional', 'list'],
      steps: [
        {
          id: 'keep-only-passing-scores',
          content: [
            { type: 'paragraph', text: 'A filter keeps some items and leaves the others out.' },
            { type: 'example', code: 'scores = [4, 9, 2, 10, 7]\nhigh_scores = []\nfor score in scores:\n    if score >= 7:\n        high_scores.append(score)' },
            { type: 'list', items: ['Visit each value.', 'Ask whether it passes the test.', 'Append it only if it passes.'] },
          ],
          activity: {
            id: 'collect-high-scores',
            kind: 'code',
            title: 'Keep the higher scores',
            prompt: 'Build a new list of scores that are 7 or higher, then print it.',
            required: true,
            starterCode: 'scores = [4, 9, 2, 10, 7]\nhigh_scores = []\nfor score in scores:\n    if score >= 7:\n        # Keep this score\n        pass\n\nprint(high_scores)',
            assessment: {
              kind: 'behavior',
              cases: [{ inputs: [], output: { mode: 'exact', lines: ['[9, 10, 7]'] } }],
              requirements: ['filter-list'],
            },
            hints: ['Append a score only inside the if.', 'Use high_scores.append(score).'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-7-lesson-8',
      order: 8,
      title: 'Validate / repeat until acceptable',
      shortTitle: 'Ask again until valid',
      summary: 'A while loop can repeat a question until the answer passes a check.',
      learningGoal: 'Use a validation loop that asks again until the entered value is acceptable.',
      conceptTags: ['algorithm', 'validation', 'while', 'input'],
      steps: [
        {
          id: 'ask-again-when-age-is-negative',
          content: [
            { type: 'paragraph', text: 'Ask for a value, check it, and ask again while it is not acceptable.' },
            { type: 'example', code: 'age = int(input("Age: "))\nwhile age < 0:\n    age = int(input("Try again: "))' },
            { type: 'callout', tone: 'tip', text: 'The loop body must update age. Otherwise the same unacceptable value would be checked forever.' },
          ],
          activity: {
            id: 'keep-asking-for-an-acceptable-age',
            kind: 'code',
            title: 'Ask again for a valid age',
            prompt: 'Ask for an age. While it is negative, ask again. Print the accepted age.',
            required: true,
            sampleInputs: ['-1', '12'],
            starterCode: 'age = int(input("Age: "))\nwhile age < 0:\n    # Ask again and update age\n    pass\n\nprint(age)',
            assessment: {
              kind: 'behavior',
              cases: [
                { inputs: ['12'], output: { mode: 'exact', lines: ['12'] }, requiredInputs: [{ inputIndex: 0, mustAppearInOutput: false }] },
                { inputs: ['-1', '12'], output: { mode: 'exact', lines: ['12'] }, requiredInputs: [{ inputIndex: 0, mustAppearInOutput: false }, { inputIndex: 1, mustAppearInOutput: false }] },
                { inputs: ['-3', '-1', '0'], output: { mode: 'exact', lines: ['0'] }, requiredInputs: [{ inputIndex: 0, mustAppearInOutput: false }, { inputIndex: 1, mustAppearInOutput: false }, { inputIndex: 2, mustAppearInOutput: false }] },
              ],
              requirements: ['input-validation-loop'],
            },
            hints: ['Put age = int(input(...)) inside the while loop.', 'The loop condition is age < 0. Stop when it is no longer true.'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-7-lesson-9',
      order: 9,
      title: 'Recognise the pattern',
      shortTitle: 'Name the algorithm',
      summary: 'Look past the story to recognise the algorithm a problem needs.',
      learningGoal: 'Select a reusable algorithmic pattern from a problem description without seeing code.',
      conceptTags: ['algorithm', 'abstraction', 'recognition'],
      steps: [
        {
          id: 'recognise-count',
          content: [{ type: 'paragraph', text: 'How many rainy days were recorded?' }],
          activity: {
            id: 'choose-the-rainy-day-pattern',
            kind: 'choice',
            title: 'Choose the pattern',
            prompt: 'Which algorithm would help answer the question?',
            required: true,
            options: [...patternChoices],
            correctOptionId: 'count',
            correctFeedback: 'Right — check each day and add 1 for every rainy one: count-if.',
            incorrectFeedback: 'The question asks how many items match a condition.',
          },
        },
        {
          id: 'recognise-best-so-far',
          content: [{ type: 'paragraph', text: 'What was the hottest day?' }],
          activity: {
            id: 'choose-the-hottest-day-pattern',
            kind: 'choice',
            title: 'Choose the pattern',
            prompt: 'Which algorithm would help find the hottest day?',
            required: true,
            options: [...patternChoices],
            correctOptionId: 'best',
            correctFeedback: 'Yes — keep the hottest value found so far as you check each day.',
            incorrectFeedback: 'You need to compare each temperature with the best one so far.',
          },
        },
        {
          id: 'recognise-filter',
          content: [{ type: 'paragraph', text: 'Which names begin with A?' }],
          activity: {
            id: 'choose-the-name-filter-pattern',
            kind: 'choice',
            title: 'Choose the pattern',
            prompt: 'Which algorithm would collect all names that pass this test?',
            required: true,
            options: [...patternChoices],
            correctOptionId: 'filter',
            correctFeedback: 'Correct — keep each name that passes the starts-with-A test.',
            incorrectFeedback: 'The result can contain several matching names, not just True or False.',
          },
        },
        {
          id: 'recognise-transform',
          content: [{ type: 'paragraph', text: 'Convert every temperature from Celsius to Fahrenheit.' }],
          activity: {
            id: 'choose-the-temperature-transform-pattern',
            kind: 'choice',
            title: 'Choose the pattern',
            prompt: 'Which algorithm changes every value and keeps the results?',
            required: true,
            options: [...patternChoices],
            correctOptionId: 'transform',
            correctFeedback: 'Exactly — transform every temperature and put each changed value in a new collection.',
            incorrectFeedback: 'Every input temperature should have a corresponding changed output temperature.',
          },
        },
        {
          id: 'recognise-search',
          content: [{ type: 'paragraph', text: 'Find whether a username exists.' }],
          activity: {
            id: 'choose-the-username-search-pattern',
            kind: 'choice',
            title: 'Choose the pattern',
            prompt: 'Which algorithm answers whether a matching username exists?',
            required: true,
            options: [...patternChoices],
            correctOptionId: 'search',
            correctFeedback: 'Right — search until you find a match, then remember that it was found.',
            incorrectFeedback: 'The result is one yes-or-no answer about whether a match exists.',
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-7-lesson-10',
      order: 10,
      title: 'Pattern transfer',
      shortTitle: 'Reuse count-if',
      summary: 'One count-if pattern can answer questions about scores, weather, or words.',
      learningGoal: 'Transfer the same count-if structure to different data and story contexts.',
      conceptTags: ['algorithm', 'pattern-transfer', 'count', 'project'],
      steps: [
        {
          id: 'count-passing-scores-again',
          content: [
            { type: 'paragraph', text: 'Count the scores that pass a test. This is the same count pattern from earlier.' },
            { type: 'example', code: 'count = 0\nfor item in items:\n    if item passes the test:\n        count = count + 1' },
          ],
          activity: {
            id: 'transfer-count-to-scores',
            kind: 'code',
            title: 'Count passing scores',
            prompt: 'Count the scores that are 7 or higher.',
            required: true,
            starterCode: 'scores = [4, 9, 2, 10, 7]\ncount = 0\nfor score in scores:\n    if score >= 7:\n        # Increase count by 1\n        pass\n\nprint(count)',
            assessment: {
              kind: 'behavior',
              cases: [{ inputs: [], output: { mode: 'exact', lines: ['3'] } }],
              requirements: ['count-if'],
            },
            hints: ['The score values are different, but the count structure is familiar.', 'Add 1 only when score >= 7.'],
          },
        },
        {
          id: 'count-rainy-days',
          content: [{ type: 'paragraph', text: 'Now count rainy days. The items are True or False, but the algorithm is still count-if.' }],
          activity: {
            id: 'transfer-count-to-weather',
            kind: 'code',
            title: 'Count rainy days',
            prompt: 'Count how many days had rain.',
            required: true,
            starterCode: 'rained = [True, False, True, True]\nrainy_days = 0\nfor did_rain in rained:\n    if did_rain:\n        # Increase rainy_days by 1\n        pass\n\nprint(rainy_days)',
            assessment: {
              kind: 'behavior',
              cases: [{ inputs: [], output: { mode: 'exact', lines: ['3'] } }],
              requirements: ['count-if'],
            },
            hints: ['The if test can use the True or False value directly.', 'Increase rainy_days by 1 inside the if.'],
          },
        },
        {
          id: 'count-long-words',
          content: [{ type: 'paragraph', text: 'Finally, count words longer than five letters. The details changed; the pattern did not.' }],
          activity: {
            id: 'transfer-count-to-word-lengths',
            kind: 'code',
            title: 'Count long words',
            prompt: 'Count the words with more than five letters.',
            required: true,
            starterCode: 'words = ["water", "planet", "sun", "library"]\nlong_words = 0\nfor word in words:\n    if len(word) > 5:\n        # Increase long_words by 1\n        pass\n\nprint(long_words)',
            assessment: {
              kind: 'behavior',
              cases: [{ inputs: [], output: { mode: 'exact', lines: ['2'] } }],
              requirements: ['count-if'],
            },
            hints: ['Use len(word) > 5 as the test.', 'Increase long_words by 1 only inside the if.'],
          },
        },
        {
          id: 'name-the-shared-structure',
          content: [
            { type: 'paragraph', text: 'These problems looked different, but each used the same count-if pattern.' },
            { type: 'list', items: ['Start a count at 0.', 'Visit each item.', 'Check a condition.', 'Add 1 when it passes.'] },
          ],
        },
      ],
      status: 'ready',
    },
  ],
}
