import type { Stage } from '../types'

export const stageSix: Stage = {
  id: 'stage-6',
  order: 6,
  title: 'Functions and Abstraction',
  description: 'Give actions names, pass in information, and produce results.',
  lessons: [
    {
      id: 'stage-6-lesson-1',
      order: 1,
      title: 'You have been using functions all along',
      shortTitle: 'Functions have a shape',
      summary: 'Recognise function calls you already know, such as print(), len(), and int().',
      learningGoal: 'Recognize a function call and use a function result in an expression.',
      conceptTags: ['function', 'call', 'built-in'],
      steps: [
        {
          id: 'spot-familiar-functions',
          content: [
            { type: 'paragraph', text: 'You have already used functions such as print(), len(), int(), and input().' },
            { type: 'example', code: 'print("hello")\nlen("python")\nint("12")\ninput("Name: ")' },
            { type: 'callout', tone: 'tip', text: 'A function call uses a function name followed by parentheses.' },
          ],
          activity: {
            id: 'recognise-a-function-call',
            kind: 'choice',
            title: 'What do they have in common?',
            prompt: 'What is the shared shape of print("hello"), len("python"), and int("12")?',
            required: true,
            options: [
              { id: 'function-call', text: 'They call a function by writing its name and parentheses.' },
              { id: 'variable-assignment', text: 'They all assign a value to a variable.' },
              { id: 'loop', text: 'They all repeat the same instructions.' },
            ],
            correctOptionId: 'function-call',
            correctFeedback: 'Right — the name tells Python which function to use, and parentheses make the call.',
            incorrectFeedback: 'Look for what comes after each function name.',
          },
        },
        {
          id: 'use-a-function-result',
          content: [{ type: 'paragraph', text: 'Some functions give a value back. You can use that value in another calculation.' }],
          activity: {
            id: 'use-length-and-conversion-functions',
            kind: 'code',
            title: 'Use functions you know',
            prompt: 'Print the number of letters in python, then print the number 12 plus 1 using int().',
            required: true,
            starterCode: 'word = "python"\n# Print the number of letters\n# Convert "12" to a number, add 1, and print it',
            assessment: {
              kind: 'behavior',
              cases: [{ inputs: [], output: { mode: 'exact', lines: ['6', '13'] } }],
              requirements: ['length-call'],
            },
            hints: ['len(word) gives back the number of letters.', 'Use int("12") + 1 in a print() call.'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-6-lesson-2',
      order: 2,
      title: 'Give an action a name',
      shortTitle: 'Define and call',
      summary: 'A function definition gives an action a name; calling it makes the action happen.',
      learningGoal: 'Tell the difference between defining a function and calling it.',
      conceptTags: ['function', 'definition', 'call'],
      steps: [
        {
          id: 'definition-does-not-run',
          content: [
            { type: 'paragraph', text: 'def gives an action a name and describes what it will do. The indented lines wait until you call the function.' },
            { type: 'example', code: 'def cheer():\n    print("You can do it!")\n\ncheer()\ncheer()' },
          ],
          activity: {
            id: 'predict-before-calling',
            kind: 'predict-output',
            title: 'Does defining it make it run?',
            prompt: 'Predict which two lines appear. The function is defined, but is not called.',
            required: true,
            code: 'print("The program starts")\ndef cheer():\n    print("You can do it!")\nprint("The program continues")',
            expectedOutput: ['The program starts', 'The program continues'],
          },
        },
        {
          id: 'call-the-named-action',
          content: [{ type: 'paragraph', text: 'Write cheer() to call the function. Try calling it twice.' }],
          activity: {
            id: 'define-and-call-cheer',
            kind: 'code',
            title: 'Make the action happen',
            prompt: 'Define cheer() so it prints You can do it!, then call it twice.',
            required: true,
            starterCode: 'def cheer():\n    # Print the message\n    pass\n\n# Call cheer twice',
            assessment: {
              kind: 'behavior',
              cases: [{ inputs: [], output: { mode: 'exact', lines: ['You can do it!', 'You can do it!'] } }],
              requirements: ['function-definition', 'function-call'],
            },
            hints: ['Put print("You can do it!") inside the indented function body.', 'Write cheer() twice after the function definition.'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-6-lesson-3',
      order: 3,
      title: 'Give a function information',
      shortTitle: 'Use one parameter',
      summary: 'A parameter is a named space for information a function receives.',
      learningGoal: 'Define a function with one parameter and use the received value.',
      conceptTags: ['function', 'parameter', 'argument'],
      steps: [
        {
          id: 'pass-a-name-in',
          content: [
            { type: 'paragraph', text: 'A parameter is a name inside the function definition. The value in the call is passed into that name.' },
            { type: 'example', code: 'def greet(name):\n    print("Hello", name)\n\ngreet("Mia")\ngreet("Leo")', caption: 'In greet("Mia"), name receives the value "Mia".' },
          ],
          activity: {
            id: 'greet-different-people',
            kind: 'code',
            title: 'Use the information you receive',
            prompt: 'Define greet(name) to print Hello followed by the name. Call it for Mia and Leo.',
            required: true,
            starterCode: 'def greet(name):\n    # Print a greeting using name\n    pass\n\ngreet("Mia")\ngreet("Leo")',
            assessment: {
              kind: 'behavior',
              cases: [{ inputs: [], output: { mode: 'exact', lines: ['Hello Mia', 'Hello Leo'] } }],
              requirements: ['function-definition', 'function-call', 'function-parameter'],
            },
            hints: ['The parameter goes between the parentheses in def greet(name):.', 'Inside the function, print("Hello", name).'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-6-lesson-4',
      order: 4,
      title: 'Multiple inputs',
      shortTitle: 'Use two parameters',
      summary: 'Function calls pass values to parameters in order.',
      learningGoal: 'Define and call a function that uses two pieces of information in order.',
      conceptTags: ['function', 'parameters', 'arguments', 'order'],
      steps: [
        {
          id: 'notice-argument-order',
          content: [
            { type: 'paragraph', text: 'A function can receive more than one value. Python matches them to parameters from left to right.' },
            { type: 'example', code: 'def show_score(name, score):\n    print(name, "scored", score)\n\nshow_score("Mia", 8)' },
          ],
          activity: {
            id: 'choose-call-argument-order',
            kind: 'choice',
            title: 'Keep the values in order',
            prompt: 'Which call sends the name first and the score second?',
            required: true,
            options: [
              { id: 'name-then-score', text: 'show_score("Mia", 8)' },
              { id: 'score-then-name', text: 'show_score(8, "Mia")' },
            ],
            correctOptionId: 'name-then-score',
            correctFeedback: 'Yes — the first value goes to name, and the second goes to score.',
            incorrectFeedback: 'Read the parameters from left to right, then match each value to its place.',
          },
        },
        {
          id: 'write-a-two-parameter-function',
          content: [{ type: 'paragraph', text: 'If you reverse the values, Python still runs the call, but the information ends up in the wrong places.' }],
          activity: {
            id: 'show-names-and-scores',
            kind: 'code',
            title: 'Show who earned each score',
            prompt: 'Define show_score(name, score), then call it for Mia with 8 and Leo with 10.',
            required: true,
            starterCode: 'def show_score(name, score):\n    # Print the name, "scored", and the score\n    pass\n\nshow_score("Mia", 8)\nshow_score("Leo", 10)',
            assessment: {
              kind: 'behavior',
              cases: [{ inputs: [], output: { mode: 'exact', lines: ['Mia scored 8', 'Leo scored 10'] } }],
              requirements: ['function-definition', 'function-call', 'multiple-parameters'],
            },
            hints: ['Put name and score inside the definition parentheses.', 'Print name, "scored", score in that order.'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-6-lesson-5',
      order: 5,
      title: 'Producing a value',
      shortTitle: 'Return a result',
      summary: 'return sends a value from a function back to the code that called it.',
      learningGoal: 'Return a calculated value and use the result of a function call.',
      conceptTags: ['function', 'return', 'value'],
      steps: [
        {
          id: 'send-back-a-calculation',
          content: [
            { type: 'paragraph', text: 'A function can calculate a value and send it back with return.' },
            { type: 'example', code: 'def double(number):\n    return number * 2\n\nresult = double(6)\nprint(result)' },
            { type: 'callout', tone: 'tip', text: 'The call double(6) gives back 12, which can be saved or used in another calculation.' },
          ],
          activity: {
            id: 'return-a-doubled-number',
            kind: 'code',
            title: 'Give the answer back',
            prompt: 'Define double(number) so it returns twice the number. Print the results for 6 and 9.',
            required: true,
            starterCode: 'def double(number):\n    # Return twice the number\n    pass\n\nprint(double(6))\nprint(double(9))',
            assessment: {
              kind: 'behavior',
              cases: [{ inputs: [], output: { mode: 'exact', lines: ['12', '18'] } }],
              requirements: ['function-definition', 'function-call', 'function-parameter', 'function-return'],
            },
            hints: ['Use return, not print, inside the function.', 'Return number * 2.'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-6-lesson-6',
      order: 6,
      title: 'return is not print',
      shortTitle: 'Return is not print',
      summary: 'print shows a value; return lets the rest of the program use it.',
      learningGoal: 'Explain and demonstrate why a printed value cannot be used as a returned result.',
      conceptTags: ['function', 'return', 'print', 'value'],
      steps: [
        {
          id: 'choose-return-for-calculation',
          content: [
            { type: 'paragraph', text: 'print shows a value on the screen. return gives a value back to the code that called the function.' },
            { type: 'example', code: 'def double(number):\n    print(number * 2)\n\n# This displays a value, but does not give it back.' },
          ],
          activity: {
            id: 'choose-the-value-producing-version',
            kind: 'choice',
            title: 'Which version can be used in a calculation?',
            prompt: 'You want answer = double(6) + 1 to work. What should double do?',
            required: true,
            options: [
              { id: 'return-value', text: 'Return number * 2 from inside the function.' },
              { id: 'print-value', text: 'Print number * 2 from inside the function.' },
            ],
            correctOptionId: 'return-value',
            correctFeedback: 'Exactly — return supplies the value that the + 1 can use.',
            incorrectFeedback: 'Printing shows a value to a person. Which action gives the value back to Python code?',
          },
        },
        {
          id: 'use-the-returned-value',
          content: [{ type: 'paragraph', text: 'Try adding 1 to the result of each call. A print-only function cannot provide a number for this calculation.' }],
          activity: {
            id: 'add-to-a-returned-result',
            kind: 'code',
            title: 'Use the result in another calculation',
            prompt: 'Make double(number) return twice its input. Print double(6) + 1 and double(9) + 1.',
            required: true,
            starterCode: 'def double(number):\n    # Return twice the number\n    pass\n\nprint(double(6) + 1)\nprint(double(9) + 1)',
            assessment: {
              kind: 'behavior',
              cases: [{ inputs: [], output: { mode: 'exact', lines: ['13', '19'] } }],
              requirements: ['function-definition', 'function-parameter', 'function-return'],
            },
            hints: ['The answer needs to be a number that Python can add 1 to.', 'Write return number * 2 inside double.'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-6-lesson-7',
      order: 7,
      title: 'Functions can be combined',
      shortTitle: 'Combine functions',
      summary: 'A returned value can become the information another function receives.',
      learningGoal: 'Trace and build nested function calls from the inside out.',
      conceptTags: ['function', 'call', 'return', 'composition'],
      steps: [
        {
          id: 'trace-combined-functions',
          content: [
            { type: 'paragraph', text: 'Python works out the inner call first, then gives that result to the outer function.' },
            { type: 'example', code: 'def double(number):\n    return number * 2\n\ndef add_one(number):\n    return number + 1\n\nanswer = add_one(double(5))' },
          ],
          activity: {
            id: 'predict-nested-function-result',
            kind: 'predict-output',
            title: 'Follow the value inside out',
            prompt: 'Predict the value printed after Python evaluates double(5), then passes it to add_one().',
            required: true,
            code: 'def double(number):\n    return number * 2\n\ndef add_one(number):\n    return number + 1\n\nanswer = add_one(double(5))\nprint(answer)',
            expectedOutput: ['11'],
          },
        },
        {
          id: 'combine-two-actions',
          content: [{ type: 'paragraph', text: 'The value returned by one function can be passed straight into another call.' }],
          activity: {
            id: 'build-a-combined-calculation',
            kind: 'code',
            title: 'Double, then add one',
            prompt: 'Define double(number) and add_one(number), then print add_one(double(5)) and add_one(double(7)).',
            required: true,
            starterCode: 'def double(number):\n    # Return twice the number\n    pass\n\ndef add_one(number):\n    # Return the number plus 1\n    pass\n\nprint(add_one(double(5)))\nprint(add_one(double(7)))',
            assessment: {
              kind: 'behavior',
              cases: [{ inputs: [], output: { mode: 'exact', lines: ['11', '15'] } }],
              requirements: ['function-definition', 'function-call', 'function-parameter', 'function-return'],
            },
            hints: ['Finish both functions with return statements.', 'Return number * 2 from double and number + 1 from add_one.'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-6-lesson-8',
      order: 8,
      title: 'Local state',
      shortTitle: 'Names inside functions',
      summary: 'Some names exist only while a function is doing its work.',
      learningGoal: 'Observe that a variable created in a function cannot be used outside it.',
      conceptTags: ['function', 'local-scope', 'name'],
      steps: [
        {
          id: 'choose-where-a-local-name-exists',
          content: [
            { type: 'paragraph', text: 'A name created inside a function belongs to that function. Some names only exist while the function is doing its work.' },
            { type: 'example', code: 'def calculate():\n    result = 10\n    print(result)\n\ncalculate()' },
          ],
          activity: {
            id: 'locate-the-local-name',
            kind: 'choice',
            title: 'Where can result be used?',
            prompt: 'In the example, where is result available?',
            required: true,
            options: [
              { id: 'inside-function', text: 'Inside calculate(), where the name was created.' },
              { id: 'everywhere', text: 'Anywhere in the program, even after calculate() finishes.' },
            ],
            correctOptionId: 'inside-function',
            correctFeedback: 'Right — result is local to calculate().',
            incorrectFeedback: 'Look at which lines are indented under calculate().',
          },
        },
        {
          id: 'observe-local-name-boundary',
          content: [{ type: 'callout', tone: 'tip', text: 'Run the example, then notice what changes when the last print(result) is outside the function.' }],
          activity: {
            id: 'observe-local-name-error',
            kind: 'code',
            title: 'Notice where the name stops existing',
            prompt: 'Run the code. Python should print 10 inside the function, then show a NameError outside it.',
            required: true,
            starterCode: 'def calculate():\n    result = 10\n    print(result)\n\ncalculate()\nprint(result)',
            assessment: {
              kind: 'runtime-error',
              exceptionName: 'NameError',
              requirements: ['function-definition', 'function-call', 'local-scope'],
            },
            hints: ['The final print(result) is not indented inside calculate().', 'A local name is available inside its function, not after the call finishes.'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-6-lesson-9',
      order: 9,
      title: 'Functions as contracts',
      shortTitle: 'Plan inputs and results',
      summary: 'Example calls describe what a function receives and what it should return.',
      learningGoal: 'Use example inputs and outputs to implement a function that meets a simple contract.',
      conceptTags: ['function', 'contract', 'examples', 'return'],
      steps: [
        {
          id: 'read-the-function-contract',
          content: [
            { type: 'paragraph', text: 'Before writing a function, ask what information goes in and what value should come out.' },
            { type: 'example', code: 'area(3, 4)  # gives back 12\narea(5, 2)  # gives back 10' },
          ],
          activity: {
            id: 'choose-area-from-examples',
            kind: 'choice',
            title: 'What could area do?',
            prompt: 'Which simple rule matches both examples for rectangle area?',
            required: true,
            options: [
              { id: 'add-sides', text: 'Return width + height.' },
              { id: 'multiply-sides', text: 'Return width * height.' },
              { id: 'return-first', text: 'Return only the width.' },
            ],
            correctOptionId: 'multiply-sides',
            correctFeedback: 'Yes — multiplying the two inputs gives 12 and 10 for these examples.',
            incorrectFeedback: 'Try the rule with both pairs of example values.',
          },
        },
        {
          id: 'implement-the-area-contract',
          content: [{ type: 'paragraph', text: 'Now write the function so both example calls produce the promised result.' }],
          activity: {
            id: 'calculate-rectangle-area',
            kind: 'code',
            title: 'Meet the example contract',
            prompt: 'Define area(width, height) so it returns width times height. Print the results for (3, 4) and (5, 2).',
            required: true,
            starterCode: 'def area(width, height):\n    # Return the rectangle area\n    pass\n\nprint(area(3, 4))\nprint(area(5, 2))',
            assessment: {
              kind: 'behavior',
              cases: [{ inputs: [], output: { mode: 'exact', lines: ['12', '10'] } }],
              requirements: ['function-definition', 'function-call', 'multiple-parameters', 'function-return'],
            },
            hints: ['The two parameters represent the width and height.', 'Return width * height.'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-6-lesson-10',
      order: 10,
      title: 'Build: mini maths toolkit',
      shortTitle: 'Mini maths toolkit',
      summary: 'Build small functions that double, test, and compare values.',
      learningGoal: 'Combine function names, parameters, conditions, and returned values in a small toolkit.',
      conceptTags: ['function', 'parameter', 'return', 'project'],
      steps: [
        {
          id: 'toolkit-double',
          content: [
            { type: 'paragraph', text: 'Start the toolkit with double(number). Example calls: double(3) gives 6; double(6) gives 12.' },
            { type: 'callout', tone: 'tip', text: "The calls are examples of the function's contract. Your code should work for both." },
          ],
          activity: {
            id: 'implement-toolkit-double',
            kind: 'code',
            title: 'Add double()',
            prompt: 'Define double(number) so it returns twice the number. Print double(3) and double(6).',
            required: true,
            starterCode: 'def double(number):\n    # Return twice the number\n    pass\n\nprint(double(3))\nprint(double(6))',
            assessment: {
              kind: 'behavior',
              cases: [{ inputs: [], output: { mode: 'exact', lines: ['6', '12'] } }],
              requirements: ['function-definition', 'function-call', 'function-parameter', 'function-return'],
            },
            hints: ['Use the parameter in the calculation.', 'Return number * 2.'],
          },
        },
        {
          id: 'toolkit-even-test',
          content: [{ type: 'paragraph', text: 'Add is_even(number). Example calls: is_even(4) gives True; is_even(7) gives False.' }],
          activity: {
            id: 'implement-toolkit-is-even',
            kind: 'code',
            title: 'Add is_even()',
            prompt: 'Define is_even(number) to return whether the number is even. Print the results for 4 and 7.',
            required: true,
            starterCode: 'def is_even(number):\n    # Return True when number is even\n    pass\n\nprint(is_even(4))\nprint(is_even(7))',
            assessment: {
              kind: 'behavior',
              cases: [{ inputs: [], output: { mode: 'exact', lines: ['True', 'False'] } }],
              requirements: ['function-definition', 'function-call', 'function-parameter', 'function-return'],
            },
            hints: ['The remainder after dividing an even number by 2 is 0.', 'Return number % 2 == 0.'],
          },
        },
        {
          id: 'toolkit-larger',
          content: [{ type: 'paragraph', text: 'Finish with larger(a, b). Example calls: larger(3, 4) gives 4; larger(5, 2) gives 5.' }],
          activity: {
            id: 'implement-toolkit-larger',
            kind: 'code',
            title: 'Add larger()',
            prompt: 'Define larger(a, b) to return the greater value. Print results for (3, 4), (5, 2), and (7, 7).',
            required: true,
            starterCode: 'def larger(a, b):\n    # Return the greater value\n    pass\n\nprint(larger(3, 4))\nprint(larger(5, 2))\nprint(larger(7, 7))',
            assessment: {
              kind: 'behavior',
              cases: [{ inputs: [], output: { mode: 'exact', lines: ['4', '5', '7'] } }],
              requirements: ['function-definition', 'function-call', 'multiple-parameters', 'function-return'],
            },
            hints: ['Compare a and b with if.', 'If a is greater, return a. Otherwise, return b.'],
          },
        },
      ],
      status: 'ready',
    },
  ],
}
