import type { Stage } from '../types'

export const stageThree: Stage = {
  id: 'stage-3',
  order: 3,
  title: 'Decisions',
  description: 'Use true-or-false questions to choose what a program does.',
  lessons: [
    {
      id: 'stage-3-lesson-1',
      order: 1,
      title: 'Questions the computer can answer',
      shortTitle: 'Comparisons',
      summary: 'A comparison asks a question whose answer is True or False.',
      learningGoal: 'Read and create simple comparisons using Python.',
      conceptTags: ['comparison', 'boolean', 'values'],
      steps: [
        {
          id: 'predict-comparison-answers',
          content: [
            { type: 'paragraph', text: 'Python can compare two values. Each comparison produces either True or False.' },
            { type: 'example', code: 'print(7 > 4)\nprint(3 == 3)\nprint(10 < 2)' },
            { type: 'callout', tone: 'tip', text: 'Two equal signs, ==, ask whether the values are equal.' },
          ],
          activity: {
            id: 'predict-comparison-results',
            kind: 'predict-output',
            title: 'Predict the answers',
            prompt: 'Write what Python will print, one answer per line.',
            required: true,
            code: 'print(7 > 4)\nprint(3 == 3)\nprint(10 < 2)',
            expectedOutput: ['True', 'True', 'False'],
            hints: ['7 is greater than 4, so the first answer is True.', 'The last comparison asks whether 10 is less than 2.'],
          },
        },
        {
          id: 'make-comparisons',
          content: [{ type: 'paragraph', text: 'Change the comparisons so both lines print True.' }],
          activity: {
            id: 'create-true-comparisons',
            kind: 'code',
            title: 'Make both comparisons true',
            prompt: 'Edit the values or comparison signs so Python prints True on both lines.',
            required: true,
            starterCode: 'print(8 >= 8)\nprint(9 != 9)',
            assessment: {
              kind: 'output-and-ast',
              expectation: { mode: 'exact', lines: ['True', 'True'] },
              requirement: 'comparison',
            },
            hints: ['>= means greater than or equal to.', '!= asks whether two values are different.'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-3-lesson-2',
      order: 2,
      title: 'Boolean values',
      shortTitle: 'True or False',
      summary: 'True and False are values Python can remember and use.',
      learningGoal: 'Store a true-or-false value and see a comparison saved as a value.',
      conceptTags: ['boolean', 'values', 'comparison'],
      steps: [
        {
          id: 'save-a-boolean-value',
          content: [
            { type: 'paragraph', text: 'True and False are values too. Python spells them with a capital first letter.' },
            { type: 'example', code: 'is_raining = True\nprint(is_raining)' },
          ],
          activity: {
            id: 'create-a-boolean-value',
            kind: 'code',
            title: 'Save a true-or-false value',
            prompt: 'Set is_raining to either True or False, then print it.',
            required: true,
            starterCode: 'is_raining = True\nprint(is_raining)',
            assessment: {
              kind: 'output-and-ast',
              expectation: { mode: 'contains', values: ['True'] },
              requirement: 'boolean-value',
            },
            hints: ['Use True or False without quotation marks.', 'The value is assigned with =, then its name can be printed.'],
          },
        },
        {
          id: 'save-the-answer-to-a-comparison',
          content: [
            { type: 'paragraph', text: 'A comparison also makes a True-or-False value. Give that answer a name to use it later.' },
            { type: 'evaluation', expression: 'temperature > 30', steps: ['31 > 30', 'True', 'is_hot = True'], caption: 'The comparison’s answer is saved' },
            { type: 'example', code: 'temperature = 31\nis_hot = temperature > 30\nprint(is_hot)' },
          ],
          activity: {
            id: 'predict-a-saved-comparison',
            kind: 'predict-output',
            title: 'Follow the comparison value',
            prompt: 'What value will Python print for is_hot?',
            required: true,
            code: 'temperature = 31\nis_hot = temperature > 30\nprint(is_hot)',
            expectedOutput: ['True'],
            hints: ['First ask whether 31 is greater than 30.', 'Python saves that comparison’s answer in is_hot.'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-3-lesson-3',
      order: 3,
      title: 'One-way decision',
      shortTitle: 'An if statement',
      summary: 'An if statement runs its indented instructions only when a question is True.',
      learningGoal: 'See a one-way decision take or skip its indented line.',
      conceptTags: ['conditional', 'if', 'trace'],
      steps: [
        {
          id: 'trace-the-true-path',
          content: [
            { type: 'paragraph', text: 'An if statement checks its question. When the answer is True, Python runs the indented line.' },
            { type: 'example', code: 'temperature = 35\nif temperature > 30:\n    print("It is hot")\nprint("Done")' },
          ],
          activity: {
            id: 'trace-hot-one-way-decision',
            kind: 'branch-trace',
            title: 'Predict the path',
            prompt: 'With temperature set to 35, will the indented message run?',
            required: true,
            code: 'temperature = 35\nif temperature > 30:\n    print("It is hot")\nprint("Done")',
            paths: [
              { id: 'message-runs', label: 'The indented message runs', lines: [3] },
              { id: 'message-skips', label: 'The indented message is skipped', lines: [], otherwise: true },
            ],
            hints: ['Compare 35 with 30.', '35 > 30 is True, so Python runs the indented line.'],
          },
        },
        {
          id: 'trace-the-skipped-path',
          content: [
            { type: 'paragraph', text: 'When the question is False, Python skips the indented line and continues after the decision.' },
          ],
          activity: {
            id: 'trace-cool-one-way-decision',
            kind: 'branch-trace',
            title: 'Now follow the other outcome',
            prompt: 'Change the value to 20. The final Done message still runs. Does the indented message run?',
            required: true,
            code: 'temperature = 20\nif temperature > 30:\n    print("It is hot")\nprint("Done")',
            paths: [
              { id: 'message-runs', label: 'The indented message runs', lines: [3] },
              { id: 'message-skips', label: 'The indented message is skipped', lines: [], otherwise: true },
            ],
            hints: ['20 > 30 is False.', 'The decision line runs, but its indented body is skipped.'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-3-lesson-4',
      order: 4,
      title: 'Two possible paths',
      shortTitle: 'if and else',
      summary: 'else gives a program a second path when the if question is False.',
      learningGoal: 'Use both outcomes of a decision, including a value at the boundary.',
      conceptTags: ['conditional', 'if', 'else', 'input'],
      steps: [
        {
          id: 'predict-which-path-runs',
          content: [
            { type: 'paragraph', text: 'if and else offer two paths. Only one path runs for each value.' },
            { type: 'example', code: 'age = 14\nif age >= 13:\n    print("Teen")\nelse:\n    print("Child")' },
          ],
          activity: {
            id: 'predict-age-path',
            kind: 'branch-trace',
            title: 'Choose the age path',
            prompt: 'If age is 14, which message will Python print?',
            required: true,
            code: 'age = 14\nif age >= 13:\n    print("Teen")\nelse:\n    print("Child")',
            paths: [
              { id: 'teen', label: 'The Teen path', lines: [3] },
              { id: 'child', label: 'The Child path', lines: [5] },
            ],
            hints: ['Check whether 14 is greater than or equal to 13.', 'The if path runs when that comparison is True.'],
          },
        },
        {
          id: 'write-a-two-path-program',
          content: [{ type: 'paragraph', text: 'Now make the choice depend on an age entered when the program runs. Try 12, 13, and 14.' }],
          activity: {
            id: 'classify-an-age',
            kind: 'code',
            title: 'Choose between two paths',
            prompt: 'Ask for an age. Print Teen for 13 or older and Child otherwise.',
            required: true,
            starterCode: 'age = int(input("Age? "))\nif age >= 13:\n    print("Teen")\nelse:\n    print("Child")',
            sampleInputs: ['14'],
            assessment: {
              kind: 'behavior',
              requirements: ['if-else'],
              cases: [
                { inputs: ['12'], output: { mode: 'exact', lines: ['Child'] }, requiredInputs: [{ inputIndex: 0, mustAppearInOutput: false }] },
                { inputs: ['13'], output: { mode: 'exact', lines: ['Teen'] }, requiredInputs: [{ inputIndex: 0, mustAppearInOutput: false }] },
                { inputs: ['14'], output: { mode: 'exact', lines: ['Teen'] }, requiredInputs: [{ inputIndex: 0, mustAppearInOutput: false }] },
              ],
            },
            hints: ['Convert the answer from input() with int().', 'Use age >= 13 for one path, and else for the other.'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-3-lesson-5',
      order: 5,
      title: 'Boundaries matter',
      shortTitle: 'Check the boundary',
      summary: 'At the exact boundary, > and >= can give different answers.',
      learningGoal: 'Test just below, at, and just above a decision boundary.',
      conceptTags: ['comparison', 'boundary', 'testing'],
      steps: [
        {
          id: 'notice-the-boundary',
          content: [
            { type: 'paragraph', text: '> means strictly greater. >= also includes equality.' },
            { type: 'example', code: 'age = 13\nprint(age > 13)\nprint(age >= 13)' },
            { type: 'callout', tone: 'tip', text: 'A boundary is the exact value where a decision changes.' },
          ],
          activity: {
            id: 'predict-boundary-comparisons',
            kind: 'predict-output',
            title: 'Check three ages',
            prompt: 'Predict > 13 first and >= 13 second for ages 12, 13, and 14.',
            required: true,
            code: 'age = 12\nprint(age > 13, age >= 13)\nage = 13\nprint(age > 13, age >= 13)\nage = 14\nprint(age > 13, age >= 13)',
            expectedOutput: ['False False', 'False True', 'True True'],
            hints: ['At 12, neither comparison is true.', 'At 13, >= includes the boundary but > does not.'],
          },
        },
        {
          id: 'test-your-own-boundary',
          content: [{ type: 'paragraph', text: 'Use the three nearby ages again in a program that asks for the age.' }],
          activity: {
            id: 'compare-boundary-operators',
            kind: 'code',
            title: 'Compare both operators',
            prompt: 'Read an age, then print age > 13 and age >= 13 on separate lines.',
            required: true,
            starterCode: 'age = int(input("Age? "))\nprint(age > 13)\nprint(age >= 13)',
            sampleInputs: ['13'],
            assessment: {
              kind: 'behavior',
              requirements: ['comparison'],
              cases: [
                { inputs: ['12'], output: { mode: 'exact', lines: ['False', 'False'] }, requiredInputs: [{ inputIndex: 0, mustAppearInOutput: false }] },
                { inputs: ['13'], output: { mode: 'exact', lines: ['False', 'True'] }, requiredInputs: [{ inputIndex: 0, mustAppearInOutput: false }] },
                { inputs: ['14'], output: { mode: 'exact', lines: ['True', 'True'] }, requiredInputs: [{ inputIndex: 0, mustAppearInOutput: false }] },
              ],
            },
            hints: ['Keep the two comparison lines in this order: > first, >= second.', 'At 13, the first answer is False and the second is True.'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-3-lesson-6',
      order: 6,
      title: 'More than two paths',
      shortTitle: 'Add an elif path',
      summary: 'elif checks another question when the earlier question was False.',
      learningGoal: 'Build and trace a three-way decision while noticing why order matters.',
      conceptTags: ['conditional', 'elif', 'order'],
      steps: [
        {
          id: 'trace-three-score-paths',
          content: [
            { type: 'paragraph', text: 'Python checks each condition from top to bottom. It stops after the first True path.' },
            { type: 'example', code: 'score = 72\nif score >= 80:\n    print("Gold")\nelif score >= 60:\n    print("Silver")\nelse:\n    print("Bronze")' },
            { type: 'callout', tone: 'note', text: 'If the broadest condition came first, it could catch values meant for a later path.' },
          ],
          activity: {
            id: 'trace-the-elif-path',
            kind: 'branch-trace',
            title: 'Follow the first matching path',
            prompt: 'With score 72, which message appears? The other path lines are skipped.',
            required: true,
            code: 'score = 72\nif score >= 80:\n    print("Gold")\nelif score >= 60:\n    print("Silver")\nelse:\n    print("Bronze")',
            paths: [
              { id: 'gold', label: 'Gold', lines: [3] },
              { id: 'silver', label: 'Silver', lines: [5] },
              { id: 'bronze', label: 'Bronze', lines: [7] },
            ],
            hints: ['72 is not at least 80, so Python checks the next question.', '72 is at least 60, so the Silver path runs.'],
          },
        },
        {
          id: 'build-three-score-paths',
          content: [{ type: 'paragraph', text: 'Try scores in all three ranges. Notice what changes if you put the 60-point condition first.' }],
          activity: {
            id: 'classify-a-score',
            kind: 'code',
            title: 'Create three score outcomes',
            prompt: 'Read a score and print Gold for 80+, Silver for 60–79, and Bronze below 60.',
            required: true,
            starterCode: 'score = int(input("Score? "))\nif score >= 80:\n    print("Gold")\nelif score >= 60:\n    print("Silver")\nelse:\n    print("Bronze")',
            sampleInputs: ['72'],
            assessment: {
              kind: 'behavior',
              requirements: ['elif'],
              cases: [
                { inputs: ['90'], output: { mode: 'exact', lines: ['Gold'] }, requiredInputs: [{ inputIndex: 0, mustAppearInOutput: false }] },
                { inputs: ['72'], output: { mode: 'exact', lines: ['Silver'] }, requiredInputs: [{ inputIndex: 0, mustAppearInOutput: false }] },
                { inputs: ['45'], output: { mode: 'exact', lines: ['Bronze'] }, requiredInputs: [{ inputIndex: 0, mustAppearInOutput: false }] },
              ],
            },
            hints: ['Check the highest boundary first: score >= 80.', 'Use elif score >= 60 before the final else.'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-3-lesson-7',
      order: 7,
      title: 'Combining conditions',
      shortTitle: 'Both must be true',
      summary: 'and makes a combined question true only when both parts are true.',
      learningGoal: 'Combine two comparisons with and and test when either part fails.',
      conceptTags: ['logical-and', 'comparison', 'conditional'],
      steps: [
        {
          id: 'see-both-comparisons',
          content: [
            { type: 'paragraph', text: 'The ride needs two things to be true: the age is high enough and the height is high enough.' },
            { type: 'example', code: 'age = 12\nheight = 145\nprint(age >= 10)\nprint(height >= 140)\nif age >= 10 and height >= 140:\n    print("You can ride")' },
            { type: 'evaluation', expression: 'True and True', steps: ['Both parts are True', 'The whole question is True'], caption: 'and needs both parts' },
          ],
          activity: {
            id: 'trace-two-true-conditions',
            kind: 'branch-trace',
            title: 'Follow the combined question',
            prompt: 'With age 12 and height 145, does the ride message run?',
            required: true,
            code: 'age = 12\nheight = 145\nprint(age >= 10)\nprint(height >= 140)\nif age >= 10 and height >= 140:\n    print("You can ride")',
            paths: [
              { id: 'ride', label: 'The ride message runs', lines: [6] },
              { id: 'wait', label: 'The ride message is skipped', lines: [], otherwise: true },
            ],
            hints: ['12 >= 10 is True, and 145 >= 140 is True.', 'Both sides of and are True, so the whole question is True.'],
          },
        },
        {
          id: 'test-both-requirements',
          content: [{ type: 'paragraph', text: 'Make the decision use both answers. Try changing only one answer at a time.' }],
          activity: {
            id: 'check-two-ride-requirements',
            kind: 'code',
            title: 'Require both conditions',
            prompt: 'Ask for age and height. Print You can ride only when age is at least 10 and height is at least 140.',
            required: true,
            starterCode: 'age = int(input("Age? "))\nheight = int(input("Height? "))\nif age >= 10 and height >= 140:\n    print("You can ride")\nelse:\n    print("Not yet")',
            sampleInputs: ['12', '145'],
            assessment: {
              kind: 'behavior',
              requirements: ['conditional', 'comparison', 'logical-and'],
              cases: [
                { inputs: ['12', '145'], output: { mode: 'exact', lines: ['You can ride'] }, requiredInputs: [{ inputIndex: 0, mustAppearInOutput: false }, { inputIndex: 1, mustAppearInOutput: false }] },
                { inputs: ['12', '139'], output: { mode: 'exact', lines: ['Not yet'] }, requiredInputs: [{ inputIndex: 0, mustAppearInOutput: false }, { inputIndex: 1, mustAppearInOutput: false }] },
                { inputs: ['9', '150'], output: { mode: 'exact', lines: ['Not yet'] }, requiredInputs: [{ inputIndex: 0, mustAppearInOutput: false }, { inputIndex: 1, mustAppearInOutput: false }] },
              ],
            },
            hints: ['Use int(input()) for each number.', 'Join the two comparisons in one if line with and.'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-3-lesson-8',
      order: 8,
      title: 'Either condition can be enough',
      shortTitle: 'At least one is true',
      summary: 'or makes a combined question true when either part is true.',
      learningGoal: 'Complete and apply a four-row truth table for or.',
      conceptTags: ['logical-or', 'truth-table', 'conditional'],
      steps: [
        {
          id: 'no-condition-is-true',
          content: [
            { type: 'paragraph', text: 'The school is closed if it is a weekend or a holiday. For or, either True answer is enough.' },
            { type: 'example', code: 'is_weekend = False\nis_holiday = False\nif is_weekend or is_holiday:\n    print("No school")\nelse:\n    print("School")' },
          ],
          activity: {
            id: 'truth-table-or-neither',
            kind: 'choice',
            title: 'Truth table · neither is true',
            prompt: 'If it is not a weekend and not a holiday, what will the program print?',
            required: true,
            options: [
              { id: 'no-school', text: 'No school' },
              { id: 'school', text: 'School' },
            ],
            correctOptionId: 'school',
            correctFeedback: 'Right — False or False is False, so the else path runs.',
            incorrectFeedback: 'Neither condition is True, so the combined or question is False.',
          },
        },
        {
          id: 'only-the-weekend-is-true',
          content: [{ type: 'paragraph', text: 'Now one of the two conditions is True.' }],
          activity: {
            id: 'truth-table-or-weekend',
            kind: 'choice',
            title: 'Truth table · weekend only',
            prompt: 'If it is a weekend but not a holiday, what will the program print?',
            required: true,
            options: [
              { id: 'no-school', text: 'No school' },
              { id: 'school', text: 'School' },
            ],
            correctOptionId: 'no-school',
            correctFeedback: 'Yes — one True condition is enough for or.',
            incorrectFeedback: 'The weekend condition is True, so the or question is True.',
          },
        },
        {
          id: 'only-the-holiday-is-true',
          content: [{ type: 'paragraph', text: 'The same is true when the other condition is True instead.' }],
          activity: {
            id: 'truth-table-or-holiday',
            kind: 'choice',
            title: 'Truth table · holiday only',
            prompt: 'If it is a holiday but not a weekend, what will the program print?',
            required: true,
            options: [
              { id: 'no-school', text: 'No school' },
              { id: 'school', text: 'School' },
            ],
            correctOptionId: 'no-school',
            correctFeedback: 'Right — the holiday condition alone is enough.',
            incorrectFeedback: 'The holiday condition is True, so the or question is True.',
          },
        },
        {
          id: 'both-conditions-are-true',
          content: [{ type: 'paragraph', text: 'The last row has both conditions True. The result is still True.' }],
          activity: {
            id: 'truth-table-or-both',
            kind: 'choice',
            title: 'Truth table · both are true',
            prompt: 'If it is both a weekend and a holiday, what will the program print?',
            required: true,
            options: [
              { id: 'no-school', text: 'No school' },
              { id: 'school', text: 'School' },
            ],
            correctOptionId: 'no-school',
            correctFeedback: 'Exactly — the result stays True when both parts are True.',
            incorrectFeedback: 'At least one is True (in this case, both), so the or question is True.',
          },
        },
        {
          id: 'use-or-in-a-program',
          content: [{ type: 'paragraph', text: 'Now use or in a program with answers that can change.' }],
          activity: {
            id: 'decide-with-either-condition',
            kind: 'code',
            title: 'Use either condition',
            prompt: 'Ask whether it is a weekend and a holiday. Print No school if either answer is yes; otherwise print School.',
            required: true,
            starterCode: 'is_weekend = input("Weekend? ").strip().lower() == "yes"\nis_holiday = input("Holiday? ").strip().lower() == "yes"\nif is_weekend or is_holiday:\n    print("No school")\nelse:\n    print("School")',
            sampleInputs: ['no', 'no'],
            assessment: {
              kind: 'behavior',
              requirements: ['logical-or'],
              cases: [
                { inputs: ['no', 'no'], output: { mode: 'exact', lines: ['School'] }, requiredInputs: [{ inputIndex: 0, mustAppearInOutput: false }, { inputIndex: 1, mustAppearInOutput: false }] },
                { inputs: ['yes', 'no'], output: { mode: 'exact', lines: ['No school'] }, requiredInputs: [{ inputIndex: 0, mustAppearInOutput: false }, { inputIndex: 1, mustAppearInOutput: false }] },
                { inputs: ['no', 'yes'], output: { mode: 'exact', lines: ['No school'] }, requiredInputs: [{ inputIndex: 0, mustAppearInOutput: false }, { inputIndex: 1, mustAppearInOutput: false }] },
                { inputs: ['yes', 'yes'], output: { mode: 'exact', lines: ['No school'] }, requiredInputs: [{ inputIndex: 0, mustAppearInOutput: false }, { inputIndex: 1, mustAppearInOutput: false }] },
              ],
            },
            hints: ['Compare each answer with the text "yes".', 'Join the two named conditions with or.'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-3-lesson-9',
      order: 9,
      title: 'Negation',
      shortTitle: 'The opposite with not',
      summary: 'not flips a True answer to False, and a False answer to True.',
      learningGoal: 'Read and use not to check the opposite of a condition.',
      conceptTags: ['logical-not', 'boolean', 'conditional'],
      steps: [
        {
          id: 'follow-the-not-condition',
          content: [
            { type: 'paragraph', text: 'not reverses a True-or-False value. If a door is not locked, it can open.' },
            { type: 'example', code: 'is_locked = False\nif not is_locked:\n    print("Door can open")\nelse:\n    print("Keep it closed")' },
          ],
          activity: {
            id: 'trace-not-locked',
            kind: 'branch-trace',
            title: 'Follow the opposite',
            prompt: 'is_locked is False. Does not is_locked make the if question True?',
            required: true,
            code: 'is_locked = False\nif not is_locked:\n    print("Door can open")\nelse:\n    print("Keep it closed")',
            paths: [
              { id: 'open', label: 'Door can open', lines: [3] },
              { id: 'closed', label: 'Keep it closed', lines: [5] },
            ],
            hints: ['is_locked is False.', 'not False becomes True, so the if path runs.'],
          },
        },
        {
          id: 'use-not-with-an-answer',
          content: [{ type: 'paragraph', text: 'Ask whether the door is locked and decide whether it can open.' }],
          activity: {
            id: 'check-lock-with-not',
            kind: 'code',
            title: 'Check the opposite',
            prompt: 'Read yes or no. Use not so the door-open message appears only when it is not locked.',
            required: true,
            starterCode: 'is_locked = input("Is it locked? ").strip().lower() == "yes"\nif not is_locked:\n    print("Door can open")\nelse:\n    print("Keep it closed")',
            sampleInputs: ['no'],
            assessment: {
              kind: 'behavior',
              requirements: ['logical-not', 'if-else'],
              cases: [
                { inputs: ['no'], output: { mode: 'exact', lines: ['Door can open'] }, requiredInputs: [{ inputIndex: 0, mustAppearInOutput: false }] },
                { inputs: ['yes'], output: { mode: 'exact', lines: ['Keep it closed'] }, requiredInputs: [{ inputIndex: 0, mustAppearInOutput: false }] },
              ],
            },
            hints: ['The comparison with "yes" gives is_locked a True-or-False value.', 'Put not before is_locked in the if condition.'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-3-lesson-10',
      order: 10,
      title: 'Decision challenge',
      shortTitle: 'Build a recommendation',
      summary: 'Combine comparisons and decisions to make a useful recommendation.',
      learningGoal: 'Build a small recommendation program from input and familiar conditions.',
      conceptTags: ['project', 'input', 'conditional', 'comparison', 'logical-and', 'logical-not'],
      steps: [{
        id: 'build-a-weather-recommendation',
        content: [
          { type: 'paragraph', text: 'Combine decisions to make a recommendation from the temperature and rain answer.' },
          { type: 'list', items: ['Ask for the temperature and whether it is raining.', 'If it is at least 30 and not raining, suggest a hat and water.', 'Otherwise, recommend an umbrella when it is raining, warm clothes below 15, or enjoying the weather.'] },
          { type: 'example', caption: 'One possible run', code: 'Temperature? 32\nIs it raining? no\nWear a hat and take water.' },
          { type: 'callout', tone: 'tip', text: 'Use elif when another question should be checked only after the earlier one is False.' },
        ],
        activity: {
          id: 'create-a-weather-recommendation',
          kind: 'code',
          title: 'Build your recommendation program',
          prompt: 'Ask for a temperature and a yes/no rain answer. Test the recommendation with several different combinations.',
          required: true,
          starterCode: 'temperature = int(input("Temperature? "))\nis_raining = input("Is it raining? ").strip().lower() == "yes"\nif temperature >= 30 and not is_raining:\n    print("Wear a hat and take water.")\nelif is_raining:\n    print("Take an umbrella.")\nelif temperature < 15:\n    print("Wear something warm.")\nelse:\n    print("Enjoy the weather.")',
          sampleInputs: ['32', 'no'],
          assessment: {
            kind: 'behavior',
            requirements: ['conditional', 'comparison', 'elif', 'logical-and', 'logical-not'],
            cases: [
              { inputs: ['32', 'no'], output: { mode: 'exact', lines: ['Wear a hat and take water.'] }, requiredInputs: [{ inputIndex: 0, mustAppearInOutput: false }, { inputIndex: 1, mustAppearInOutput: false }] },
              { inputs: ['32', 'yes'], output: { mode: 'exact', lines: ['Take an umbrella.'] }, requiredInputs: [{ inputIndex: 0, mustAppearInOutput: false }, { inputIndex: 1, mustAppearInOutput: false }] },
              { inputs: ['10', 'no'], output: { mode: 'exact', lines: ['Wear something warm.'] }, requiredInputs: [{ inputIndex: 0, mustAppearInOutput: false }, { inputIndex: 1, mustAppearInOutput: false }] },
              { inputs: ['20', 'no'], output: { mode: 'exact', lines: ['Enjoy the weather.'] }, requiredInputs: [{ inputIndex: 0, mustAppearInOutput: false }, { inputIndex: 1, mustAppearInOutput: false }] },
            ],
          },
          hints: [
            'Convert the temperature answer with int(). Compare the rain answer with "yes".',
            'Check the hot and dry case first using and and not.',
            'Use elif for the rain and cold cases, followed by a final else.',
          ],
        },
      }],
      status: 'ready',
    },
  ],
}
