import type { Stage } from '../types'

export const stageTwo: Stage = {
  id: 'stage-2',
  order: 2,
  title: 'Names, State, and Input',
  description: 'Name values, see how they change, and receive information.',
  lessons: [
    {
      id: 'stage-2-lesson-1',
      order: 1,
      title: 'Giving a value a name',
      shortTitle: 'Name a value',
      summary: 'A name lets a program refer to a value again.',
      learningGoal: 'Create a named value and use the name to display it.',
      conceptTags: ['variables', 'names', 'values'],
      steps: [
        {
          id: 'see-a-name-point-to-a-value',
          content: [
            { type: 'paragraph', text: 'A name gives Python a way to remember a value.' },
            { type: 'example', code: 'score = 10\nprint(score)' },
            { type: 'callout', tone: 'tip', text: 'Read this as: give the name score the value 10.' },
          ],
          activity: {
            id: 'predict-named-score',
            kind: 'predict-state',
            title: 'Follow the name',
            prompt: 'After line 1, what value will score refer to?',
            required: true,
            code: 'score = 10\nprint(score)',
            line: 1,
            variable: 'score',
            expectedValue: '10',
            choices: ['score', '10', '0'],
            hints: ['The right side of = is the value.', 'score is given the value 10.'],
          },
        },
        {
          id: 'create-and-use-a-name',
          content: [{ type: 'paragraph', text: 'Now make a named value of your own and ask Python to display it.' }],
          activity: {
            id: 'create-a-named-value',
            kind: 'code',
            title: 'Give a value a name',
            prompt: 'Change print() so it displays the value using the name score, rather than repeating 10.',
            required: true,
            starterCode: 'score = 10\nprint(10)',
            assessment: {
              kind: 'output-and-ast',
              expectation: { mode: 'exact', lines: ['10'] },
              requirement: 'named-value',
            },
            hints: ['Put a name on the left of =.', 'Use that same name inside print().'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-2-lesson-2',
      order: 2,
      title: 'The right side happens first',
      shortTitle: 'Right side first',
      summary: 'Python works out the value on the right before giving it a name.',
      learningGoal: 'Trace a calculation before its result is stored.',
      conceptTags: ['assignment', 'expressions', 'evaluation-order'],
      steps: [
        {
          id: 'predict-the-stored-result',
          content: [
            { type: 'paragraph', text: 'Python calculates 5 + 3 first. Then it gives the result to score.' },
            { type: 'evaluation', expression: '5 + 3', steps: ['8'], caption: 'First work out the right side' },
            { type: 'example', code: 'score = 5 + 3\nprint(score)' },
          ],
          activity: {
            id: 'predict-calculation-before-assignment',
            kind: 'predict-state',
            title: 'Follow the calculation',
            prompt: 'After line 1, what value will score refer to?',
            required: true,
            code: 'score = 5 + 3\nprint(score)',
            line: 1,
            variable: 'score',
            expectedValue: '8',
            choices: ['5', '3', '8', '53'],
            hints: ['Calculate the right side before thinking about score.', '5 + 3 is 8.'],
          },
        },
        {
          id: 'create-a-calculated-value',
          content: [{ type: 'paragraph', text: 'Use a different calculation, save its result under a name, then print the name.' }],
          activity: {
            id: 'calculate-before-saving',
            kind: 'code',
            title: 'Calculate, then remember',
            prompt: 'Make an expression that produces 15, save it in a variable, and print the variable.',
            required: true,
            starterCode: 'answer = 7 * 2\nprint(answer)',
            assessment: {
              kind: 'output-and-ast',
              expectation: { mode: 'exact', lines: ['15'] },
              requirement: 'named-value',
            },
            hints: ['The expression goes on the right of =.', 'Use the name from the left side inside print().'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-2-lesson-3',
      order: 3,
      title: 'Names make programs meaningful',
      shortTitle: 'Meaningful names',
      summary: 'A useful name helps another person understand what a value represents.',
      learningGoal: 'Choose names that communicate what values mean.',
      conceptTags: ['variables', 'communication', 'readability'],
      steps: [
        {
          id: 'compare-two-program-stories',
          content: [
            { type: 'paragraph', text: 'Both programs calculate the same amount. One gives the values names that explain what they mean.' },
            { type: 'example', caption: 'The numbers alone', code: 'print(12 * 4)' },
            { type: 'example', caption: 'Names tell a story', code: 'price = 12\nquantity = 4\nprint(price * quantity)' },
          ],
          activity: {
            id: 'choose-the-clearer-program',
            kind: 'choice',
            title: 'Which program communicates more?',
            prompt: 'Which version gives a reader more clues about what the numbers mean?',
            required: true,
            options: [
              { id: 'numbers-only', text: 'print(12 * 4) — it has fewer lines.' },
              { id: 'named-values', text: 'price and quantity — their names explain the calculation.' },
            ],
            correctOptionId: 'named-values',
            correctFeedback: 'Yes — good names communicate the meaning of values to another person.',
            incorrectFeedback: 'Fewer lines can be useful, but the names explain why these numbers are being multiplied.',
          },
        },
        {
          id: 'write-a-readable-calculation',
          content: [{ type: 'paragraph', text: 'Use names that make this small calculation easy to understand.' }],
          activity: {
            id: 'name-price-and-quantity',
            kind: 'code',
            title: 'Tell the calculation’s story',
            prompt: 'Change the calculation to multiply price and quantity instead of repeating the numbers.',
            required: true,
            starterCode: 'price = 12\nquantity = 4\nprint(12 * 4)',
            assessment: {
              kind: 'output-and-ast',
              expectation: { mode: 'exact', lines: ['48'] },
              requirement: { kind: 'operation-uses-names', operation: 'multiply', names: ['price', 'quantity'] },
            },
            hints: ['The names are already set up above.', 'Use both names on the same print() line, with * between them.'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-2-lesson-4',
      order: 4,
      title: 'Values can change over time',
      shortTitle: 'Changing values',
      summary: 'A name refers to its current value; a later assignment replaces the earlier one.',
      learningGoal: 'Distinguish a value a name had earlier from the value it has now.',
      conceptTags: ['state', 'assignment', 'time'],
      misconceptions: ['A variable keeps every value ever assigned to it.'],
      steps: [
        {
          id: 'watch-score-change',
          content: [
            { type: 'paragraph', text: 'The first print happens before score changes. The second happens after Python gives score a new value.' },
            { type: 'example', code: 'score = 10\nprint(score)\nscore = 20\nprint(score)' },
            { type: 'callout', tone: 'tip', text: 'score has one current value at a time. A new assignment replaces the old value.' },
          ],
          activity: {
            id: 'predict-changing-score-output',
            kind: 'predict-output',
            title: 'Predict both moments',
            prompt: 'What will the first print show? What will the second print show?',
            required: true,
            code: 'score = 10\nprint(score)\nscore = 20\nprint(score)',
            expectedOutput: ['10', '20'],
            hints: ['The first print comes before score = 20.', 'The second print comes after score is changed.'],
          },
        },
        {
          id: 'change-a-named-value',
          content: [{ type: 'paragraph', text: 'Change a named value twice and display what it was before and after.' }],
          activity: {
            id: 'reassign-the-same-name',
            kind: 'code',
            title: 'Show a value changing',
            prompt: 'Add an assignment between the print() calls that changes score to 20.',
            required: true,
            starterCode: 'score = 10\nprint(score)\n\n# Change score to 20 here\n\nprint(score)',
            assessment: {
              kind: 'output-and-ast',
              expectation: { mode: 'exact', lines: ['10', '20'] },
              requirement: 'variable-reassignment',
            },
            hints: ['Add the new assignment between the two print() calls.', 'Use the same name: score = 20.'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-2-lesson-5',
      order: 5,
      title: 'The famous x = x + 1',
      shortTitle: 'Add one',
      summary: 'Assignment reads the old value on the right, then stores the new value on the left.',
      learningGoal: 'Read an assignment right side first and follow a value as it changes.',
      conceptTags: ['assignment', 'state', 'expressions'],
      steps: [
        {
          id: 'predict-add-one',
          content: [
            { type: 'paragraph', text: 'The name score appears on both sides of the = sign. Start by reading the right side using the value score already has.' },
            { type: 'evaluation', expression: 'score = score + 1', steps: ['score = 10 + 1', 'score = 11'], caption: 'score was 10 before this line' },
            { type: 'example', code: 'score = 10\nscore = score + 1\nprint(score)' },
          ],
          activity: {
            id: 'predict-incremented-score',
            kind: 'predict-state',
            title: 'Predict the new value',
            prompt: 'After line 2, what value will score refer to?',
            required: true,
            code: 'score = 10\nscore = score + 1\nprint(score)',
            line: 2,
            variable: 'score',
            expectedValue: '11',
            choices: ['10', '11', '1'],
            hints: ['Use the old score on the right side: 10.', '10 + 1 is 11.'],
          },
        },
        {
          id: 'make-a-value-increase',
          content: [{ type: 'paragraph', text: 'Now start with a different value and increase it in the same way.' }],
          activity: {
            id: 'increment-a-number',
            kind: 'code',
            title: 'Increase a value',
            prompt: 'This prints 21, but it hardcodes the answer. Change the second line so Python adds 1 to score’s current value.',
            required: true,
            starterCode: 'score = 20\nscore = 21\nprint(score)',
            assessment: {
              kind: 'output-and-ast',
              expectation: { mode: 'exact', lines: ['21'] },
              requirement: 'variable-increment',
            },
            hints: ['Read the current value from score on the right side of =.', 'Use score = score + 1 on the second line.'],
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'stage-2-lesson-6',
      order: 6,
      title: 'Trace multiple pieces of state',
      shortTitle: 'Trace the table',
      summary: 'Several named values can change independently as the program runs.',
      learningGoal: 'Complete a multi-variable trace table using real execution checkpoints.',
      conceptTags: ['state', 'tracing', 'variables'],
      steps: [{
        id: 'fill-the-state-trace-table',
        content: [
          { type: 'paragraph', text: 'Trace first, before running. After each listed line, write the current value of coins and stars. Use — when a name has not been given a value yet.' },
        ],
        activity: {
          id: 'complete-coins-and-stars-table',
          kind: 'trace-table',
          title: 'Fill in the changing values',
          prompt: 'Complete every cell before running the program. Python will check your table against the state at each real execution checkpoint.',
          required: true,
          code: 'coins = 5\nstars = 2\n\ncoins = coins + 3\nstars = stars + 1\ncoins = coins - 2\nprint(coins, stars)',
          variables: ['coins', 'stars'],
          checkpoints: [
            { id: 'after-coins-start', line: 1, label: 'after line 1' },
            { id: 'after-stars-start', line: 2, label: 'after line 2' },
            { id: 'after-coins-plus', line: 4, label: 'after line 4' },
            { id: 'after-stars-plus', line: 5, label: 'after line 5' },
            { id: 'after-coins-minus', line: 6, label: 'after line 6' },
          ],
          hints: ['After line 1, coins is 5 and stars has no value yet: enter —.', 'Line 4 adds 3 coins; line 5 adds 1 star; line 6 removes 2 coins.'],
        },
      }],
      status: 'ready',
    },
    {
      id: 'stage-2-lesson-7',
      order: 7,
      title: 'Programs can receive information',
      shortTitle: 'Ask a question',
      summary: 'input() pauses a program so a person can provide information.',
      learningGoal: 'Ask for one piece of information and use the answer in output.',
      conceptTags: ['input', 'output', 'interaction'],
      steps: [{
        id: 'ask-for-a-name',
        content: [
          { type: 'paragraph', text: 'input() pauses Python and lets a person type an answer. The program can save that answer under a name and use it later.' },
          { type: 'example', code: 'name = input("What is your name? ")\nprint("Hello", name)' },
          { type: 'list', items: ['Person types an answer → program receives it → program responds.'] },
        ],
        activity: {
          id: 'greet-the-person',
          kind: 'code',
          title: 'Ask and greet',
          prompt: 'Change the greeting so it includes the name that was entered. Try different names.',
          required: true,
          starterCode: 'name = input("What is your name? ")\nprint("Hello")',
          sampleInputs: ['Maya'],
          assessment: {
            kind: 'behavior',
            cases: [
              { inputs: ['Maya'], output: { mode: 'exact', lines: ['Hello Maya'] }, requiredInputs: [{ inputIndex: 0 }] },
              { inputs: ['Ada'], output: { mode: 'exact', lines: ['Hello Ada'] }, requiredInputs: [{ inputIndex: 0 }] },
            ],
          },
          hints: ['The name is already saved in the variable name.', 'Use that variable in print(), after "Hello".'],
        },
      }],
      status: 'ready',
    },
    {
      id: 'stage-2-lesson-8',
      order: 8,
      title: 'Input is text',
      shortTitle: 'Input is text',
      summary: 'An answer from input() starts as text, even when it looks like a number.',
      learningGoal: 'Notice why text from input cannot be used as a number without conversion.',
      conceptTags: ['input', 'text', 'types', 'errors'],
      steps: [{
        id: 'notice-text-plus-number',
        content: [
          { type: 'paragraph', text: 'Try an age that looks like a number. input() gives the program text, so adding 1 will not work yet.' },
          { type: 'example', code: 'age = input("How old are you? ")\nprint(age + 1)' },
          { type: 'callout', tone: 'note', text: 'The characters "12" are text. The number 12 is a different value, even though they look similar.' },
        ],
        activity: {
          id: 'observe-input-text-type-error',
          kind: 'code',
          title: 'Notice what input gives you',
          prompt: 'Run the program and enter 12. Read the TypeError and notice that the answer from input() is text.',
          required: true,
          starterCode: 'age = input("How old are you? ")\nprint(age + 1)',
          sampleInputs: ['12'],
          assessment: { kind: 'runtime-error', exceptionName: 'TypeError' },
          hints: ['input() gives the program what was typed as text.', 'Python cannot add the text "12" and the number 1.'],
        },
      }],
      status: 'ready',
    },
    {
      id: 'stage-2-lesson-9',
      order: 9,
      title: 'Converting representations',
      shortTitle: 'Turn text into a number',
      summary: 'int() converts text containing whole-number digits into a number.',
      learningGoal: 'Convert an input answer before doing arithmetic with it.',
      conceptTags: ['input', 'conversion', 'types'],
      steps: [{
        id: 'convert-age-then-add',
        content: [
          { type: 'paragraph', text: 'int() turns digit text into a whole number. Save the converted value under a name, then use it in the calculation.' },
          { type: 'example', code: 'age_text = input("How old are you? ")\nage = int(age_text)\nprint(age + 1)' },
          { type: 'evaluation', expression: '"12"', steps: ['int("12")', '12'], caption: 'Text becomes a number' },
        ],
        activity: {
          id: 'convert-and-calculate-age',
          kind: 'code',
          title: 'Calculate the next age',
          prompt: 'Repair the TypeError: convert the answer from input() to a number before adding 1. The check tries more than one age.',
          required: true,
          starterCode: 'age = input("How old are you? ")\nprint(age + 1)',
          sampleInputs: ['12'],
          assessment: {
            kind: 'behavior',
            cases: [
              { inputs: ['12'], output: { mode: 'exact', lines: ['13'] }, requiredInputs: [{ inputIndex: 0, mustAppearInOutput: false }] },
              { inputs: ['7'], output: { mode: 'exact', lines: ['8'] }, requiredInputs: [{ inputIndex: 0, mustAppearInOutput: false }] },
            ],
          },
          hints: ['input() gives you text, even when the answer looks like a number.', 'Use int(...) to convert the answer before adding 1.'],
        },
      }],
      status: 'ready',
    },
    {
      id: 'stage-2-lesson-10',
      order: 10,
      title: 'Build: the future machine',
      shortTitle: 'Future machine',
      summary: 'Combine two answers, named values, conversion, and arithmetic in a small program.',
      learningGoal: 'Recombine names, input, conversion, arithmetic, and output in a complete program.',
      conceptTags: ['project', 'input', 'variables', 'conversion', 'arithmetic'],
      steps: [{
        id: 'build-the-future-machine',
        content: [
          { type: 'paragraph', text: 'Build a tiny program that asks for a name and an age, then tells the person about next year and five years from now.' },
          { type: 'list', items: ['Ask for both answers.', 'Remember each answer with a useful name.', 'Convert the age text before calculating.', 'Use the answers in the three-line response.'] },
          { type: 'example', caption: 'One possible interaction', code: 'What is your name? Maya\nHow old are you? 12\nHi Maya!\nNext year you will be 13\nIn five years you will be 17' },
        ],
        activity: {
          id: 'create-the-future-machine',
          kind: 'code',
          title: 'Build the program',
          prompt: 'Ask for a name and age. Print a greeting, the age next year, and the age in five years. Test the answers with the real prompts.',
          required: true,
          starterCode: 'name = input("What is your name? ")\nage_text = input("How old are you? ")\n\n# Convert age_text to a number\nage = 0\n\n# Print a greeting using name\n# Print the age next year\n# Print the age in five years',
          sampleInputs: ['Maya', '12'],
          assessment: {
            kind: 'behavior',
            cases: [
              {
                inputs: ['Maya', '12'],
                output: { mode: 'exact', lines: ['Hi Maya!', 'Next year you will be 13', 'In five years you will be 17'] },
                requiredInputs: [{ inputIndex: 0 }, { inputIndex: 1, mustAppearInOutput: false }],
              },
              {
                inputs: ['Ada', '9'],
                output: { mode: 'exact', lines: ['Hi Ada!', 'Next year you will be 10', 'In five years you will be 14'] },
                requiredInputs: [{ inputIndex: 0 }, { inputIndex: 1, mustAppearInOutput: false }],
              },
            ],
          },
          hints: [
            'Use one input() for the name and another for the age.',
            'The age from input() is text. Convert it with int() before adding.',
            'Use name and age in the three print() lines, then try both sets of answers.',
          ],
        },
      }],
      status: 'ready',
    },
  ],
}
