import type { Module } from '../types'

export const fundamentalsModule: Module = {
  id: 'fundamentals',
  order: 1,
  title: 'Getting Python to do things',
  description: 'Start with the edit, run, and output cycle.',
  lessons: [
    {
      id: 'saying-something',
      order: 1,
      title: 'Hello Python',
      shortTitle: 'Hello Python',
      summary: 'Use print() to make Python display words.',
      learningGoal: 'Understand that running a program can produce visible output.',
      conceptTags: ['execution', 'output'],
      steps: [{
        id: 'make-python-speak',
        content: [
          { type: 'paragraph', text: 'The print() command makes Python show something on the screen.' },
          { type: 'callout', tone: 'tip', text: 'Text goes inside quotation marks.' },
          { type: 'example', code: 'print("Hello!")' },
        ],
        activity: {
          id: 'print-a-greeting',
          kind: 'code',
          title: 'Try it yourself',
          prompt: 'Change the code so Python prints Hello Python!',
          required: true,
          starterCode: 'print("Hello!")',
          hints: [
            'Keep print() and change the words inside the quotation marks.',
            'The exact words are Hello Python!',
          ],
          assessment: {
            kind: 'output',
            expectation: { mode: 'exact', lines: ['Hello Python!'] },
          },
        },
      }],
      status: 'ready',
    },
    {
      id: 'your-own-text',
      order: 2,
      title: 'Printing your own text',
      shortTitle: 'Your own text',
      summary: 'Change the text Python displays.',
      learningGoal: 'Use strings and print several lines in order.',
      conceptTags: ['text', 'sequence', 'output'],
      steps: [{
        id: 'print-two-lines',
        content: [
          { type: 'paragraph', text: 'Text inside quotation marks is called a string. You can change it to say anything you like.' },
          { type: 'callout', tone: 'note', text: 'Two print() commands make two lines.' },
          { type: 'example', code: 'print("My name is Alex")\nprint("I like pizza")' },
        ],
        activity: {
          id: 'write-your-own-lines',
          kind: 'code',
          title: 'Try it yourself',
          prompt: 'Make Python print two lines: one with your name and one with something you like.',
          required: true,
          starterCode: 'print("My name is Alex")\nprint("I like pizza")',
          hints: [
            'Edit the words between the quotation marks.',
            'Leave one print() command on each line.',
          ],
          assessment: {
            kind: 'output',
            expectation: { mode: 'line-count', count: 2 },
            reject: ['My name is Alex\nI like pizza'],
          },
        },
      }],
      status: 'ready',
    },
    {
      id: 'numbers-and-maths',
      order: 3,
      title: 'Numbers and maths',
      shortTitle: 'Numbers and maths',
      summary: 'Python can calculate answers for you.',
      learningGoal: 'Recognise that expressions calculate values which can be printed.',
      conceptTags: ['numbers', 'expressions', 'output'],
      misconceptions: ['Numbers need quotation marks to be printed.'],
      steps: [
        {
          id: 'predict-a-calculation',
          content: [
            { type: 'paragraph', text: 'Python can work with numbers. Use +, -, *, and / to calculate.' },
            { type: 'callout', tone: 'tip', text: 'Numbers do not need quotation marks when you want Python to calculate them.' },
          ],
          activity: {
            id: 'predict-addition',
            kind: 'predict-output',
            title: 'Predict, then run',
            prompt: 'What do you think Python will print?',
            required: true,
            code: 'print(2 + 3)',
            expectedOutput: ['5'],
          },
        },
        {
          id: 'calculate-a-new-answer',
          content: [
            { type: 'paragraph', text: 'The symbols are instructions too: + adds, - subtracts, * multiplies, and / divides.' },
            { type: 'example', code: 'print(10 * 4)' },
          ],
          activity: {
            id: 'print-a-calculation',
            kind: 'code',
            title: 'Your turn',
            prompt: 'Make Python calculate and print the answer to 12 + 8.',
            required: true,
            starterCode: 'print(2 + 3)',
            hints: [
              'Put the calculation inside print().',
              'Your code could be print(12 + 8).',
            ],
            assessment: { kind: 'output', expectation: { mode: 'exact', lines: ['20'] } },
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'variables',
      order: 4,
      title: 'Remembering things',
      shortTitle: 'Variables',
      summary: 'Give a value a name so Python can remember it.',
      learningGoal: 'Create and use a name that refers to a text value.',
      conceptTags: ['variables', 'assignment', 'state'],
      steps: [
        {
          id: 'follow-a-value',
          content: [
            { type: 'paragraph', text: 'A variable lets Python remember a value using a name. Watch what happens when the value changes.' },
            { type: 'example', code: 'score = 10\nscore = 20\nprint(score)' },
          ],
          activity: {
            id: 'predict-a-changing-value',
            kind: 'predict-state',
            title: 'Follow the name',
            prompt: 'What value will score refer to after line 2 runs?',
            required: true,
            code: 'score = 10\nscore = 20\nprint(score)',
            line: 2,
            variable: 'score',
            expectedValue: '20',
            choices: ['10', '20', '30'],
            hints: ['Each assignment changes the value referred to by score.', 'Read line 2 from right to left: the new value is 20.'],
          },
        },
        {
          id: 'name-a-value',
          content: [
            { type: 'paragraph', text: 'Now give a text value your own name and ask Python to show it.' },
            { type: 'callout', tone: 'note', text: 'Put the value in quotes. Use the variable name without quotes when you print it.' },
            { type: 'example', code: 'name = "Alex"\nprint(name)' },
          ],
          activity: {
            id: 'create-a-text-variable',
            kind: 'code',
            title: 'Try it yourself',
            prompt: 'Create a variable containing your favourite food, then print the variable.',
            required: true,
            starterCode: 'food = "pizza"\nprint(food)',
            hints: [
              'Choose a name, such as favourite_food.',
              'Put your favourite food in quotation marks, then print the name you chose.',
            ],
            assessment: { kind: 'ast', requirement: 'text-variable', rejectOutput: ['pizza'] },
          },
        },
      ],
      status: 'ready',
    },
    {
      id: 'values-in-sentences',
      order: 5,
      title: 'Putting values into sentences',
      shortTitle: 'Values in sentences',
      summary: 'Use a variable inside a sentence with an f-string.',
      learningGoal: 'Use a text variable as part of a sentence printed by Python.',
      conceptTags: ['variables', 'strings', 'f-strings'],
      steps: [{
        id: 'insert-a-value',
        content: [
          { type: 'paragraph', text: 'An f-string lets you put a variable inside a sentence. Put f before the quotes and the variable inside curly brackets.' },
          { type: 'callout', tone: 'tip', text: 'For example: f"I like {food}".' },
          { type: 'example', code: 'food = "pizza"\nprint(f"I like {food}")' },
        ],
        activity: {
          id: 'use-a-value-in-a-sentence',
          kind: 'code',
          title: 'Try it yourself',
          prompt: 'Create a variable for your favourite food and print a sentence that includes it.',
          required: true,
          starterCode: 'food = "pizza"\nprint(f"I like {food}")',
          hints: [
            'Change the value in the variable to something you like.',
            'Keep the f before the opening quotation mark and put the variable inside {curly brackets}.',
          ],
          assessment: { kind: 'ast', requirement: 'variable-in-sentence', rejectOutput: ['I like pizza'] },
        },
      }],
      status: 'ready',
    },
  ],
}
